// CONFIGURACIÓN DE CORREO ADMINISTRADOR (Garantiza independencia de scripts)
if (typeof ADMIN_EMAIL === 'undefined') {
  var ADMIN_EMAIL = 'correadediego30@gmail.com';
}

// BASE DE DATOS EXTENSA Y PROFESIONAL DE INGLÉS (A1, A2, B1)
const englishLessonsData = {
  'A1': [
    {
      id: 'a1_greetings',
      title: '1. Greetings, Farewells & Personal Information (Saludos, Despedidas e Información Personal)',
      summary: 'Aprende a saludar, despedirte e intercambiar datos básicos de presentación personal en entornos formales e informales.',
      description: 'En este tema fundacional aprenderás las estructuras para entablar comunicación básica. Diferenciarás entre registros formales e informales, y aprenderás a proporcionar e interpretar datos personales esenciales como nombres, ocupaciones, nacionalidades y edades.',
      grammar: 'Estructuras de interacción básica:\n- Formulación de saludos: "Good morning/afternoon/evening" (Formal) vs. "Hi/Hey" (Informal).\n- Preguntas directas de información personal: "What is your name?", "Where are you from?", "How old are you?".\n- Estructura de respuesta: Sujeto + Verbo To Be + Complemento (ej. "I am Maria", "I am 20 years old").',
      examples: [
        'Formal: "Hello, good morning. How are you today?" / "I am fine, thank you. And you?"',
        'Informal: "Hey! What is up?" / "Not much, just chilling."',
        'Presentación: "My name is Carlos. I am from Spain and I am twenty-five years old."',
        'Despedida formal: "It was a pleasure meeting you. Goodbye." / "Likewise, have a nice day."'
      ],
      vocabulary: [
        { word: 'Hello', phonetic: '[jel-óu]', trans: 'Hola (Formal)' },
        { word: 'Hi', phonetic: '[jái]', trans: 'Hola (Informal)' },
        { word: 'Good morning', phonetic: '[gud mór-ning]', trans: 'Buenos días' },
        { word: 'Good afternoon', phonetic: '[gud af-ter-nún]', trans: 'Buenas tardes' },
        { word: 'Good evening', phonetic: '[gud ív-ning]', trans: 'Buenas noches (saludo)' },
        { word: 'Good night', phonetic: '[gud náit]', trans: 'Buenas noches (despedida)' },
        { word: 'Goodbye', phonetic: '[gud-bái]', trans: 'Adiós' },
        { word: 'Bye', phonetic: '[bái]', trans: 'Chao / Adiós' },
        { word: 'See you later', phonetic: '[sí iú léi-ter]', trans: 'Hasta luego' },
        { word: 'See you tomorrow', phonetic: '[sí iú tu-mó-rou]', trans: 'Hasta mañana' },
        { word: 'Name', phonetic: '[néim]', trans: 'Nombre' },
        { word: 'First name', phonetic: '[férst néim]', trans: 'Primer nombre' },
        { word: 'Last name', phonetic: '[last néim]', trans: 'Apellido' },
        { word: 'Surname', phonetic: '[sér-neim]', trans: 'Apellido (Reino Unido)' },
        { word: 'Country', phonetic: '[kán-tri]', trans: 'País' },
        { word: 'Nationality', phonetic: '[nash-o-ná-li-ti]', trans: 'Nacionalidad' },
        { word: 'City', phonetic: '[sí-ti]', trans: 'Ciudad' },
        { word: 'Address', phonetic: '[a-drés]', trans: 'Dirección' },
        { word: 'Phone number', phonetic: '[fóun nám-ber]', trans: 'Número de teléfono' },
        { word: 'Email address', phonetic: '[í-meil a-drés]', trans: 'Correo electrónico' },
        { word: 'Age', phonetic: '[éidzh]', trans: 'Edad' },
        { word: 'Job', phonetic: '[dzhob]', trans: 'Trabajo / Ocupación' },
        { word: 'Occupation', phonetic: '[ok-iu-péi-shon]', trans: 'Ocupación' },
        { word: 'Nice to meet you', phonetic: '[náis tu mít iú]', trans: 'Gusto en conocerte' },
        { word: 'Pleasure', phonetic: '[plé-zhur]', trans: 'Placer' },
        { word: 'How are you?', phonetic: '[jáu ar iú]', trans: '¿Cómo estás?' },
        { word: 'How is it going?', phonetic: '[jáu iz it góu-ing]', trans: '¿Cómo te va?' },
        { word: 'Fine', phonetic: '[fáin]', trans: 'Bien' },
        { word: 'Great', phonetic: '[gréit]', trans: 'Genial / Excelente' },
        { word: 'Bad', phonetic: '[bad]', trans: 'Malo' },
        { word: 'So-so', phonetic: '[sóu-sóu]', trans: 'Más o menos' },
        { word: 'Thanks', phonetic: '[thanks]', trans: 'Gracias' },
        { word: 'Thank you', phonetic: '[thank iú]', trans: 'Gracias (Formal)' },
        { word: 'You are welcome', phonetic: '[iú ar uél-kom]', trans: 'De nada' },
        { word: 'Please', phonetic: '[plís]', trans: 'Por favor' },
        { word: 'Excuse me', phonetic: '[eks-kiús mí]', trans: 'Disculpe / Con permiso' },
        { word: 'Sorry', phonetic: '[só-ri]', trans: 'Lo siento' },
        { word: 'Mr.', phonetic: '[mis-ter]', trans: 'Señor' },
        { word: 'Mrs.', phonetic: '[mi-siz]', trans: 'Señora (casada)' },
        { word: 'Ms.', phonetic: '[miz]', trans: 'Señorita / Señora' },
        { word: 'Friend', phonetic: '[frend]', trans: 'Amigo/a' },
        { word: 'Classmate', phonetic: '[klás-meit]', trans: 'Compañero de clase' },
        { word: 'Colleague', phonetic: '[kó-lig]', trans: 'Compañero de trabajo' },
        { word: 'Student', phonetic: '[estú-dent]', trans: 'Estudiante' },
        { word: 'Teacher', phonetic: '[tí-cher]', trans: 'Profesor/a' },
        { word: 'Man', phonetic: '[man]', trans: 'Hombre' },
        { word: 'Woman', phonetic: '[ú-man]', trans: 'Mujer' },
        { word: 'Boy', phonetic: '[bói]', trans: 'Niño' },
        { word: 'Girl', phonetic: '[gérl]', trans: 'Niña' },
        { word: 'Single', phonetic: '[síng-gl]', trans: 'Soltero/a' },
        { word: 'Married', phonetic: '[má-rid]', trans: 'Casado/a' }
      ]
    },
    {
      id: 'a1_tobe',
      title: '2. Subject Pronouns & Verb To Be (Pronombres Personales y Verbo Ser/Estar)',
      summary: 'Dominio absoluto de la conjugación y uso del verbo "To Be" en forma afirmativa, negativa e interrogativa.',
      description: 'El verbo "To Be" es el pilar de la gramática inglesa. Equivale a dos verbos en español: "Ser" (identidad, origen, profesión) y "Estar" (ubicación, estados temporales). Requiere memorizar la concordancia exacta con los pronombres personales.',
      grammar: 'Conjugación en Presente:\n- Pronombres: I (Yo), You (Tú/Ustedes), He (Él), She (Ella), It (Eso/Cosa/Animal), We (Nosotros), They (Ellos). \n- Afirmativo: Sujeto + am/is/are + Complemento. (I am, He/She/It is, You/We/They are).\n- Negativo: Sujeto + am/is/are + not + Complemento. Contracciones: isn\'t, aren\'t.\n- Interrogativo: Am/Is/Are + Sujeto + Complemento + ?',
      examples: [
        'Afirmativo (Identidad): "She is an architect." (Ella es arquitecta.)',
        'Afirmativo (Estado): "They are very happy today." (Ellos están muy felices hoy.)',
        'Negativo: "He is not (isn\'t) at home right now." (Él no está en casa en este momento.)',
        'Interrogativo: "Are you ready for the exam?" / "Yes, I am." / "No, I am not."'
      ],
      vocabulary: [
        { word: 'I', phonetic: '[ái]', trans: 'Yo' },
        { word: 'You', phonetic: '[iú]', trans: 'Tú / Usted / Ustedes' },
        { word: 'He', phonetic: '[jí]', trans: 'Él' },
        { word: 'She', phonetic: '[shí]', trans: 'Ella' },
        { word: 'It', phonetic: '[it]', trans: 'Eso / Ello (Cosa/Animal)' },
        { word: 'We', phonetic: '[uí]', trans: 'Nosotros / Nosotras' },
        { word: 'They', phonetic: '[déi]', trans: 'Ellos / Ellas' },
        { word: 'Am', phonetic: '[am]', trans: 'Soy / Estoy' },
        { word: 'Is', phonetic: '[iz]', trans: 'Es / Está' },
        { word: 'Are', phonetic: '[ar]', trans: 'Somos / Estamos / Son / Están' },
        { word: 'Not', phonetic: '[not]', trans: 'No (Adverbio de negación)' },
        { word: 'Happy', phonetic: '[já-pi]', trans: 'Feliz' },
        { word: 'Sad', phonetic: '[sad]', trans: 'Triste' },
        { word: 'Angry', phonetic: '[án-gri]', trans: 'Enojado/a' },
        { word: 'Tired', phonetic: '[tái-erd]', trans: 'Cansado/a' },
        { word: 'Hungry', phonetic: '[ján-gri]', trans: 'Hambriento/a' },
        { word: 'Thirsty', phonetic: '[thers-ti]', trans: 'Sediento/a' },
        { word: 'Sick', phonetic: '[sik]', trans: 'Enfermo/a' },
        { word: 'Busy', phonetic: '[bí-zi]', trans: 'Ocupado/a' },
        { word: 'Late', phonetic: '[léit]', trans: 'Tarde' },
        { word: 'Early', phonetic: '[ér-li]', trans: 'Temprano' },
        { word: 'Cold', phonetic: '[kóuld]', trans: 'Frío / Con frío' },
        { word: 'Hot', phonetic: '[jot]', trans: 'Caliente / Con calor' },
        { word: 'Bored', phonetic: '[bord]', trans: 'Aburrido/a' },
        { word: 'Scared', phonetic: '[skerd]', trans: 'Asustado/a' },
        { word: 'Doctor', phonetic: '[dók-tor]', trans: 'Médico/a' },
        { word: 'Nurse', phonetic: '[ners]', trans: 'Enfermero/a' },
        { word: 'Engineer', phonetic: '[en-dzhi-níer]', trans: 'Ingeniero/a' },
        { word: 'Driver', phonetic: '[drái-ver]', trans: 'Conductor/a' },
        { word: 'Chef', phonetic: '[shef]', trans: 'Cocinero/a' },
        { word: 'Artist', phonetic: '[ár-tist]', trans: 'Artista' },
        { word: 'Police officer', phonetic: '[po-lís ó-fi-ser]', trans: 'Oficial de policía' },
        { word: 'Actor', phonetic: '[ák-tor]', trans: 'Actor' },
        { word: 'Actress', phonetic: '[ák-tres]', trans: 'Actriz' },
        { word: 'Writer', phonetic: '[rái-ter]', trans: 'Escritor/a' },
        { word: 'Home', phonetic: '[jóum]', trans: 'Hogar / Casa' },
        { word: 'Work', phonetic: '[wúerk]', trans: 'Trabajo' },
        { word: 'School', phonetic: '[eskúl]', trans: 'Escuela' },
        { word: 'Hospital', phonetic: '[jós-pi-tal]', trans: 'Hospital' },
        { word: 'Store', phonetic: '[estór]', trans: 'Tienda' },
        { word: 'Park', phonetic: '[park]', trans: 'Parque' },
        { word: 'Tall', phonetic: '[tol]', trans: 'Alto/a' },
        { word: 'Short', phonetic: '[short]', trans: 'Bajo/a / Corto/a' },
        { word: 'Young', phonetic: '[iáng]', trans: 'Joven' },
        { word: 'Old', phonetic: '[óuld]', trans: 'Viejo/a / Mayor' },
        { word: 'Smart', phonetic: '[es-márt]', trans: 'Inteligente' },
        { word: 'Kind', phonetic: '[káind]', trans: 'Amable' },
        { word: 'Funny', phonetic: '[fá-ni]', trans: 'Divertido/a' },
        { word: 'Quiet', phonetic: '[kuái-et]', trans: 'Callado/a / Tranquilo' },
        { word: 'Strong', phonetic: '[estrong]', trans: 'Fuerte' }
      ]
    },
    {
      id: 'a1_present_simple',
      title: '3. Present Simple Tense & Auxiliaries Do/Does (Presente Simple)',
      summary: 'Estructuración gramatical para hablar de rutinas, hábitos, hechos generales y verdades absolutas.',
      description: 'El Presente Simple describe hábitos continuos y hechos permanentes. Su aspecto técnico principal reside en la modificación del verbo en la tercera persona del singular (He, She, It) y el uso obligatorio de los auxiliares "Do" y "Does" para negar y preguntar.',
      grammar: 'Reglas Gramaticales: \n1. Afirmativo: Sujeto + Verbo Base (+s/es/ies para He/She/It) + Complemento.\n Regla 3ra Persona: Verbos terminados en -o, -sh, -ch, -x, -ss agregan "-es" (Go -> Goes, Watch -> Watches). Verbos en consonante + y cambian a "-ies" (Study -> Studies).\n2. Negativo: Sujeto + do not (don\'t) / does not (doesn\'t) + Verbo en Forma Base + Complemento.\n3. Interrogativo: Do / Does + Sujeto + Verbo en Forma Base + Complemento + ?',
      examples: [
        'Afirmativo (I/You/We/They): "I work in an office every day." (Trabajo en una oficina todos los días.)',
        'Afirmativo (He/She/It): "She drinks coffee every morning." (Ella bebe café todas las mañanas.)',
        'Negativo: "He does not (doesn\'t) eat meat." (Él no come carne.)',
        'Interrogativo: "Do you play video games?" / "Yes, I do." / "No, I don\'t."'
      ],
      vocabulary: [
        { word: 'Like', phonetic: '[láik]', trans: 'Gustar' },
        { word: 'Love', phonetic: '[lov]', trans: 'Amar / Encantar' },
        { word: 'Hate', phonetic: '[héit]', trans: 'Odiar' },
        { word: 'Live', phonetic: '[liv]', trans: 'Vivir' },
        { word: 'Work', phonetic: '[wúerk]', trans: 'Trabajar' },
        { word: 'Study', phonetic: '[es-tá-di]', trans: 'Estudiar' },
        { word: 'Play', phonetic: '[pléi]', trans: 'Jugar / Tocar instrumento' },
        { word: 'Eat', phonetic: '[ít]', trans: 'Comer' },
        { word: 'Drink', phonetic: '[drink]', trans: 'Beber / Tomar' },
        { word: 'Sleep', phonetic: '[es-líp]', trans: 'Dormir' },
        { word: 'Read', phonetic: '[ríd]', trans: 'Leer' },
        { word: 'Write', phonetic: '[ráit]', trans: 'Escribir' },
        { word: 'Speak', phonetic: '[es-pík]', trans: 'Hablar' },
        { word: 'Listen', phonetic: '[lís-n]', trans: 'Escuchar' },
        { word: 'Watch', phonetic: '[uótch]', trans: 'Mirar / Observar' },
        { word: 'Go', phonetic: '[góu]', trans: 'Ir' },
        { word: 'Come', phonetic: '[kom]', trans: 'Venir' },
        { word: 'Do', phonetic: '[dú]', trans: 'Hacer' },
        { word: 'Make', phonetic: '[méik]', trans: 'Hacer / Fabricar' },
        { word: 'Have', phonetic: '[jav]', trans: 'Tener' },
        { word: 'Want', phonetic: '[uónt]', trans: 'Querer' },
        { word: 'Need', phonetic: '[níd]', trans: 'Necesitar' },
        { word: 'Understand', phonetic: '[an-der-stánd]', trans: 'Entender' },
        { word: 'Know', phonetic: '[nóu]', trans: 'Saber / Conocer' },
        { word: 'Think', phonetic: '[think]', trans: 'Pensar' },
        { word: 'Buy', phonetic: '[bái]', trans: 'Comprar' },
        { word: 'Sell', phonetic: '[sel]', trans: 'Vender' },
        { word: 'Cook', phonetic: '[kuk]', trans: 'Cocinar' },
        { word: 'Clean', phonetic: '[klín]', trans: 'Limpiar' },
        { word: 'Wash', phonetic: '[uósh]', trans: 'Lavar' },
        { word: 'Drive', phonetic: '[dráiv]', trans: 'Conducir' },
        { word: 'Walk', phonetic: '[wuók]', trans: 'Caminar' },
        { word: 'Run', phonetic: '[ran]', trans: 'Correr' },
        { word: 'Always', phonetic: '[ól-weis]', trans: 'Siempre' },
        { word: 'Usually', phonetic: '[iú-zhua-li]', trans: 'Usualmente' },
        { word: 'Often', phonetic: '[ó-fen]', trans: 'A menudo' },
        { word: 'Sometimes', phonetic: '[sóm-taims]', trans: 'A veces' },
        { word: 'Never', phonetic: '[né-ver]', trans: 'Nunca' },
        { word: 'Every day', phonetic: '[évri déi]', trans: 'Todos los días' },
        { word: 'Every week', phonetic: '[évri uík]', trans: 'Todas las semanas' },
        { word: 'In the morning', phonetic: '[in de mór-ning]', trans: 'Por la mañana' },
        { word: 'In the afternoon', phonetic: '[in de af-ter-nún]', trans: 'Por la tarde' },
        { word: 'At night', phonetic: '[at náit]', trans: 'Por la noche' },
        { word: 'Breakfast', phonetic: '[brék-fast]', trans: 'Desayuno' },
        { word: 'Lunch', phonetic: '[lantch]', trans: 'Almuerzo' },
        { word: 'Dinner', phonetic: '[dí-ner]', trans: 'Cena' },
        { word: 'Coffee', phonetic: '[kó-fi]', trans: 'Café' },
        { word: 'Tea', phonetic: '[tí]', trans: 'Té' },
        { word: 'Water', phonetic: '[uó-ter]', trans: 'Agua' },
        { word: 'Food', phonetic: '[fúd]', trans: 'Comida' }
      ]
    },
    {
      id: 'a1_demonstratives',
      title: '4. Demonstratives & Articles (Demostrativos y Artículos)',
      summary: 'Identificación de objetos en espacio y cantidad mediante This, That, These, Those y artículos A, An, The.',
      description: 'Uso técnico de demostrativos para señalar elementos según número (singular/plural) y distancia física/temporal (cerca/lejos). Integración de artículos definidos e indefinidos para especificar sustantivos.',
      grammar: 'Estructuras Gramaticales: \n1. Demostrativos:\n - Singular / Cerca: This (Este/Esta/Esto) + verbo singular.\n - Singular/Lejos: That (Aquel/Ese/Eso/Esa) + verbo singular.\n - Plural/Cerca: These (Estos/Estas) + verbo plural.\n - Plural / Lejos: Those (Aquellos/Aquellas/Esos/Esas) + verbo plural.\n2. Artículos Indefinidos (A / An): Usados solo para sustantivos singulares contables. \n - "A": Se usa antes de sonido de consonante (a book, a university).\n - "An": Se usa antes de sonido de vocal (an apple, an hour).\n3. Artículo Definido (The): Utilizado para sustantivos específicos en singular y plural.',
      examples: [
        'Demonstrative Singular: "This computer is new, but that phone is old."',
        'Demonstrative Plural: "These keys are mine, but those boxes belong to Peter."',
        'Indefinite Article: "I need an umbrella and a raincoat."',
        'Definite Article: "The sun is shining today in the sky."'
      ],
      vocabulary: [
        { word: 'This', phonetic: '[dis]', trans: 'Este / Esta / Esto' },
        { word: 'That', phonetic: '[dat]', trans: 'Aquel / Eso / Esa' },
        { word: 'These', phonetic: '[dís]', trans: 'Estos / Estas' },
        { word: 'Those', phonetic: '[dóus]', trans: 'Aquellos / Aquellas' },
        { word: 'A/An', phonetic: '[ei/an]', trans: 'Un / Una' },
        { word: 'The', phonetic: '[de / di]', trans: 'El/La/Los / Las' },
        { word: 'Here', phonetic: '[jíer]', trans: 'Aquí' },
        { word: 'There', phonetic: '[dér]', trans: 'Allí / Allá' },
        { word: 'Over there', phonetic: '[óu-ver dér]', trans: 'Por allá' },
        { word: 'Book', phonetic: '[buk]', trans: 'Libro' },
        { word: 'Pen', phonetic: '[pen]', trans: 'Bolígrafo / Pluma' },
        { word: 'Pencil', phonetic: '[pén-sil]', trans: 'Lápiz' },
        { word: 'Notebook', phonetic: '[nóut-buk]', trans: 'Cuaderno' },
        { word: 'Table', phonetic: '[téi-bl]', trans: 'Mesa' },
        { word: 'Chair', phonetic: '[chér]', trans: 'Silla' },
        { word: 'Desk', phonetic: '[desk]', trans: 'Escritorio' },
        { word: 'Door', phonetic: '[dór]', trans: 'Puerta' },
        { word: 'Window', phonetic: '[uín-dou]', trans: 'Ventana' },
        { word: 'Key', phonetic: '[kí]', trans: 'Llave' },
        { word: 'Phone', phonetic: '[fóun]', trans: 'Teléfono' },
        { word: 'Computer', phonetic: '[kom-piú-ter]', trans: 'Computadora' },
        { word: 'Bag', phonetic: '[bag]', trans: 'Bolsa / Morral' },
        { word: 'Backpack', phonetic: '[bák-pak]', trans: 'Mochila' },
        { word: 'Wallet', phonetic: '[uó-let]', trans: 'Billetera' },
        { word: 'Purse', phonetic: '[pers]', trans: 'Bolso' },
        { word: 'Box', phonetic: '[boks]', trans: 'Caja' },
        { word: 'Car', phonetic: '[kar]', trans: 'Carro / Auto' },
        { word: 'House', phonetic: '[jáus]', trans: 'Casa' },
        { word: 'Room', phonetic: '[rúm]', trans: 'Habitación / Cuarto' },
        { word: 'Glasses', phonetic: '[glá-siz]', trans: 'Lentes / Gafas' },
        { word: 'Watch', phonetic: '[uótch]', trans: 'Reloj de pulsera' },
        { word: 'Picture', phonetic: '[pík-tchur]', trans: 'Imagen / Cuadro' },
        { word: 'Lamp', phonetic: '[lamp]', trans: 'Lámpara' },
        { word: 'Paper', phonetic: '[péi-per]', trans: 'Papel' },
        { word: 'Shoe', phonetic: '[shú]', trans: 'Zapato' },
        { word: 'Clothes', phonetic: '[klóuds]', trans: 'Ropa' },
        { word: 'Shirt', phonetic: '[shért]', trans: 'Camisa' },
        { word: 'Pants', phonetic: '[pants]', trans: 'Pantalones' },
        { word: 'Apple', phonetic: '[á-pl]', trans: 'Manzana' },
        { word: 'Orange', phonetic: '[ó-rindzh]', trans: 'Naranja' },
        { word: 'Umbrella', phonetic: '[am-bré-la]', trans: 'Sombrilla' },
        { word: 'Elephant', phonetic: '[é-le-fant]', trans: 'Elefante' },
        { word: 'Dog', phonetic: '[dog]', trans: 'Perro' },
        { word: 'Cat', phonetic: '[kat]', trans: 'Gato' },
        { word: 'Near', phonetic: '[níer]', trans: 'Cerca' },
        { word: 'Far', phonetic: '[far]', trans: 'Lejos' },
        { word: 'Big', phonetic: '[big]', trans: 'Grande' },
        { word: 'Small', phonetic: '[smol]', trans: 'Pequeño/a' },
        { word: 'New', phonetic: '[niú]', trans: 'Nuevo/a' },
        { word: 'Old', phonetic: '[óuld]', trans: 'Viejo/a' }
      ]
    },
    {
      id: 'a1_numbers_time',
      title: '5. Numbers, Telling the Time & Calendar (Números, La Hora y el Calendario)',
      summary: 'Expresión precisa de números cardinales, horas, días de la semana y meses del año.',
      description: 'Comprensión completa del sistema numérico para transacciones e intercambios temporales. Habilidad para dar y solicitar la hora utilizando formatos estructurados ("past" y "to"), así como ubicación temporal mediante fechas.',
      grammar: 'Formatos de la Hora:\n- Hora Exacta: It is [Número] o\'clock. (It is 5 o\'clock).\n- Minutos transcurridos (1-29): It is [Minutos] past / after [Hora]. O: It is half past [Hora] (y media).\n- Minutos faltantes (31-59): It is [Minutos faltantes] to [Hora siguiente]. O: It is a quarter to [Hora] (cuarto para).\n- Formato directo: It is [Hora] + [Minutos] (ej. 7:45 -> It is seven forty-five).',
      examples: [
        'Time Inquiry: "Excuse me, what time is it?" / "It is a quarter past three (3:15)."',
        'Calendar: "My birthday is on Monday, May 15th."',
        'Cardinal Numbers: "There are thirty-five students in this room."',
        'Schedule: "The class starts at eight o\'clock in the morning."'
      ],
      vocabulary: [
        { word: 'One', phonetic: '[uán]', trans: 'Uno' },
        { word: 'Two', phonetic: '[tú]', trans: 'Dos' },
        { word: 'Three', phonetic: '[thrí]', trans: 'Tres' },
        { word: 'Four', phonetic: '[fór]', trans: 'Cuatro' },
        { word: 'Five', phonetic: '[fáiv]', trans: 'Cinco' },
        { word: 'Six', phonetic: '[siks]', trans: 'Seis' },
        { word: 'Seven', phonetic: '[sé-ven]', trans: 'Siete' },
        { word: 'Eight', phonetic: '[éit]', trans: 'Ocho' },
        { word: 'Nine', phonetic: '[náin]', trans: 'Nueve' },
        { word: 'Ten', phonetic: '[ten]', trans: 'Diez' },
        { word: 'Eleven', phonetic: '[i-lé-ven]', trans: 'Once' },
        { word: 'Twelve', phonetic: '[tuélv]', trans: 'Doce' },
        { word: 'Thirteen', phonetic: '[ther-tín]', trans: 'Trece' },
        { word: 'Twenty', phonetic: '[tuén-ti]', trans: 'Veinte' },
        { word: 'Thirty', phonetic: '[ther-ti]', trans: 'Treinta' },
        { word: 'Forty', phonetic: '[fór-ti]', trans: 'Cuarenta' },
        { word: 'Fifty', phonetic: '[fíf-ti]', trans: 'Cincuenta' },
        { word: 'Hundred', phonetic: '[ján-dred]', trans: 'Cien / Ciento' },
        { word: 'Thousand', phonetic: '[tháu-zand]', trans: 'Mil' },
        { word: 'Clock', phonetic: '[klok]', trans: 'Reloj de pared' },
        { word: 'O\'clock', phonetic: '[o-klók]', trans: 'En punto' },
        { word: 'Half past', phonetic: '[jáf past]', trans: 'Y media' },
        { word: 'Quarter past', phonetic: '[kuór-ter past]', trans: 'Y cuarto' },
        { word: 'Quarter to', phonetic: '[kuór-ter tu]', trans: 'Cuarto para' },
        { word: 'Past / After', phonetic: '[past/af-ter]', trans: 'Pasadas las' },
        { word: 'To', phonetic: '[tu]', trans: 'Para (Hora)' },
        { word: 'Morning', phonetic: '[mór-ning]', trans: 'Mañana' },
        { word: 'Noon / Midday', phonetic: '[nún / míd-dei]', trans: 'Mediodía' },
        { word: 'Afternoon', phonetic: '[af-ter-nún]', trans: 'Tarde' },
        { word: 'Evening', phonetic: '[ív-ning]', trans: 'Noche (temprana)' },
        { word: 'Midnight', phonetic: '[míd-nait]', trans: 'Medianoche' },
        { word: 'Monday', phonetic: '[mán-dei]', trans: 'Lunes' },
        { word: 'Tuesday', phonetic: '[tiús-dei]', trans: 'Martes' },
        { word: 'Wednesday', phonetic: '[uéns-dei]', trans: 'Miércoles' },
        { word: 'Thursday', phonetic: '[thers-dei]', trans: 'Jueves' },
        { word: 'Friday', phonetic: '[frái-dei]', trans: 'Viernes' },
        { word: 'Saturday', phonetic: '[sá-ter-dei]', trans: 'Sábado' },
        { word: 'Sunday', phonetic: '[sán-dei]', trans: 'Domingo' },
        { word: 'January', phonetic: '[dzhá-niu-e-ri]', trans: 'Enero' },
        { word: 'February', phonetic: '[fé-bru-e-ri]', trans: 'Febrero' },
        { word: 'March', phonetic: '[martch]', trans: 'Marzo' },
        { word: 'April', phonetic: '[éi-pril]', trans: 'Abril' },
        { word: 'May', phonetic: '[méi]', trans: 'Mayo' },
        { word: 'June', phonetic: '[dzhún]', trans: 'Junio' },
        { word: 'July', phonetic: '[dzhu-lái]', trans: 'Julio' },
        { word: 'August', phonetic: '[ó-gost]', trans: 'Agosto' },
        { word: 'September', phonetic: '[sep-tém-ber]', trans: 'Septiembre' },
        { word: 'October', phonetic: '[ok-tóu-ber]', trans: 'Octubre' },
        { word: 'November', phonetic: '[no-vém-ber]', trans: 'Noviembre' },
        { word: 'December', phonetic: '[di-sém-ber]', trans: 'Diciembre' }
      ]
    },
    {
      id: 'a1_there_is_are',
      title: '6. There Is / There Are & Prepositions of Place (Existencia y Ubicación Spatial)',
      summary: 'Expresión de la existencia de elementos ("Hay") y su posición exacta en el espacio.',
      description: 'Uso de la estructura "There is" y "There are" para indicar la presencia de objetos o personas, combinada con preposiciones de lugar fundamentales para establecer relaciones espaciales.',
      grammar: 'Estructura Gramatical:\n- Singular / Incontable: There is + Sustantivo. (There is a car in the garage / There is milk in the fridge).\n- Plural: There are + Sustantivo Plural. (There are three cats on the roof).\n- Negativo: There is not (isn\'t) / There are not (aren\'t).\n- Interrogativo: Is there...? / Are there...?\n- Preposiciones principales: In (dentro), On (sobre superficie), Under (debajo), Next to (al lado de), Between (entre dos), In front of (frente a), Behind (detrás).',
      examples: [
        'Singular: "There is an apple on the table."',
        'Plural: "There are two parks in this town."',
        'Negativo: "There isn\'t any sugar in my tea."',
        'Pregunta y Ubicación: "Is there a bank near here?" / "Yes, it is next to the supermarket."'
      ],
      vocabulary: [
        { word: 'There is', phonetic: '[dér iz]', trans: 'Hay (Singular)' },
        { word: 'There are', phonetic: '[dér ar]', trans: 'Hay (Plural)' },
        { word: 'In', phonetic: '[in]', trans: 'En / Dentro de' },
        { word: 'On', phonetic: '[on]', trans: 'En / Sobre (Superficie)' },
        { word: 'Under', phonetic: '[án-der]', trans: 'Debajo de' },
        { word: 'Next to', phonetic: '[nekst tu]', trans: 'Al lado de' },
        { word: 'Behind', phonetic: '[bi-jáind]', trans: 'Detrás de' },
        { word: 'In front of', phonetic: '[in front ov]', trans: 'Frente a / Delante de' },
        { word: 'Between', phonetic: '[bi-tuín]', trans: 'Entre (dos objetos)' },
        { word: 'Among', phonetic: '[a-móng]', trans: 'Entre (varios objetos)' },
        { word: 'Above', phonetic: '[a-bóv]', trans: 'Por encima de (sin contacto)' },
        { word: 'Below', phonetic: '[bi-lóu]', trans: 'Por debajo de' },
        { word: 'Near', phonetic: '[níer]', trans: 'Cerca de' },
        { word: 'Far from', phonetic: '[far from]', trans: 'Lejos de' },
        { word: 'Inside', phonetic: '[in-sáid]', trans: 'Adentro' },
        { word: 'Outside', phonetic: '[aut-sáid]', trans: 'Afuera' },
        { word: 'Kitchen', phonetic: '[kít-chen]', trans: 'Cocina' },
        { word: 'Bathroom', phonetic: '[báth-rum]', trans: 'Baño' },
        { word: 'Bedroom', phonetic: '[béd-rum]', trans: 'Dormitorio' },
        { word: 'Living room', phonetic: '[lí-ving rum]', trans: 'Sala de estar' },
        { word: 'Dining room', phonetic: '[dái-ning rum]', trans: 'Comedor' },
        { word: 'Garage', phonetic: '[ga-rázh]', trans: 'Garaje' },
        { word: 'Garden', phonetic: '[gár-dn]', trans: 'Jardín' },
        { word: 'Balcony', phonetic: '[bál-ko-ni]', trans: 'Balcón' },
        { word: 'Sofa', phonetic: '[sóu-fa]', trans: 'Sofá' },
        { word: 'Bed', phonetic: '[bed]', trans: 'Cama' },
        { word: 'Fridge', phonetic: '[fridzh]', trans: 'Nevera / Refrigerador' },
        { word: 'Stove', phonetic: '[stóuv]', trans: 'Estufa / Cocina' },
        { word: 'Sink', phonetic: '[sink]', trans: 'Fregadero / Lavamanos' },
        { word: 'Shower', phonetic: '[sháu-er]', trans: 'Ducha' },
        { word: 'Mirror', phonetic: '[mí-ror]', trans: 'Espejo' },
        { word: 'Window', phonetic: '[uín-dou]', trans: 'Ventana' },
        { word: 'Street', phonetic: '[estrít]', trans: 'Calle' },
        { word: 'Avenue', phonetic: '[á-ve-niu]', trans: 'Avenida' },
        { word: 'City center', phonetic: '[sí-ti sén-ter]', trans: 'Centro de la ciudad' },
        { word: 'Building', phonetic: '[bíl-ding]', trans: 'Edificio' },
        { word: 'Supermarket', phonetic: '[sú-per-mar-ket]', trans: 'Supermercado' },
        { word: 'Bank', phonetic: '[bank]', trans: 'Banco' },
        { word: 'Pharmacy', phonetic: '[fár-ma-si]', trans: 'Farmacia' },
        { word: 'Restaurant', phonetic: '[rés-to-rant]', trans: 'Restaurante' },
        { word: 'Bus stop', phonetic: '[bas estop]', trans: 'Parada de autobús' },
        { word: 'Station', phonetic: '[es-téi-shon]', trans: 'Estación' },
        { word: 'Map', phonetic: '[map]', trans: 'Mapa' },
        { word: 'Corner', phonetic: '[kór-ner]', trans: 'Esquina' },
        { word: 'Floor', phonetic: '[flor]', trans: 'Piso / Suelo' },
        { word: 'Wall', phonetic: '[uól]', trans: 'Pared' },
        { word: 'Ceiling', phonetic: '[sí-ling]', trans: 'Techo (interior)' },
        { word: 'Roof', phonetic: '[rúf]', trans: 'Techo (exterior)' },
        { word: 'Keys', phonetic: '[kís]', trans: 'Llaves' },
        { word: 'Money', phonetic: '[má-ni]', trans: 'Dinero' }
      ]
    }
  ],
  'A2': [
    {
      id: 'a2_past_simple',
      title: '1. Past Simple Tense: Regular & Irregular Verbs (Pasado Simple)',
      summary: 'Expresión de acciones completadas en un momento específico del pasado.',
      description: 'El Pasado Simple describe eventos, acciones o estados finalizados en un marco temporal concluido. Requiere distinguir operativamente entre verbos regulares (que adoptan la terminación "-ed") e irregulares (que cambian su raíz totalmente), además de utilizar el auxiliar "Did" para formas negativas e interrogativas.',
      grammar: 'Reglas de Estructuración:\n1. Afirmativo:\n - Verbos Regulares: Verbo Base + -ed (Play -> Played, Walk -> Walked, Study -> Studied).\n - Verbos Irregulares: Segunda columna de la lista de verbos (Go -> Went, Buy -> Bought, See -> Saw).\n2. Negativo: Sujeto + did not (didn\'t) + Verbo en Forma Base + Complemento.\n3. Interrogativo: Did + Sujeto + Verbo en Forma Base + Complemento + ?',
      examples: [
        'Regular Afirmativo: "We visited our grandparents last weekend."',
        'Irregular Afirmativo: "She bought a new car yesterday."',
        'Negativo: "They did not (didn\'t) finish the project on time."',
        'Interrogativo: "Did you see the movie last night?" / "Yes, I did." / "No, I didn\'t."'
      ],
      vocabulary: [
        { word: 'Yesterday', phonetic: '[iés-ter-déi]', trans: 'Ayer' },
        { word: 'Last night', phonetic: '[last náit]', trans: 'Anoche' },
        { word: 'Last week', phonetic: '[last uík]', trans: 'La semana pasada' },
        { word: 'Last month', phonetic: '[last month]', trans: 'El mes pasado' },
        { word: 'Last year', phonetic: '[last iér]', trans: 'El año pasado' },
        { word: 'Ago', phonetic: '[a-góu]', trans: 'Hace (Tiempo atrás)' },
        { word: 'Was', phonetic: '[wos]', trans: 'Fue / Estaba (I, He, She, It)' },
        { word: 'Were', phonetic: '[wuer]', trans: 'Fueron / Estaban (You, We, They)' },
        { word: 'Went', phonetic: '[went]', trans: 'Fui / Fue / Fuimos (Pasado de Go)' },
        { word: 'Bought', phonetic: '[bot]', trans: 'Compró / Compré (Pasado de Buy)' },
        { word: 'Saw', phonetic: '[só]', trans: 'Vió / Vi (Pasado de See)' },
        { word: 'Ate', phonetic: '[éit]', trans: 'Comió / Comí (Pasado de Eat)' },
        { word: 'Drank', phonetic: '[drank]', trans: 'Bebió / Bebí (Pasado de Drink)' },
        { word: 'Slept', phonetic: '[slept]', trans: 'Durmió / Dormí (Pasado de Sleep)' },
        { word: 'Wrote', phonetic: '[róut]', trans: 'Escribió / Escribí (Pasado de Write)' },
        { word: 'Spoke', phonetic: '[espóuk]', trans: 'Habló / Hablé (Pasado de Speak)' },
        { word: 'Came', phonetic: '[kéim]', trans: 'Vino / Vine (Pasado de Come)' },
        { word: 'Took', phonetic: '[tuk]', trans: 'Tomó / Tomé (Pasado de Take)' },
        { word: 'Gave', phonetic: '[géiv]', trans: 'Dio / Di (Pasado de Give)' },
        { word: 'Made', phonetic: '[méid]', trans: 'Hizo / Hice (Pasado de Make)' },
        { word: 'Did', phonetic: '[did]', trans: 'Hizo / Hice (Pasado de Do / Auxiliar)' },
        { word: 'Had', phonetic: '[jad]', trans: 'Tuvo / Tuve (Pasado de Have)' },
        { word: 'Thought', phonetic: '[thot]', trans: 'Pensó / Pensé (Pasado de Think)' },
        { word: 'Knew', phonetic: '[niú]', trans: 'Sabía / Conoció (Pasado de Know)' },
        { word: 'Found', phonetic: '[fáund]', trans: 'Encontró / Encontré (Pasado de Find)' },
        { word: 'Left', phonetic: '[left]', trans: 'Salió / Dejó (Pasado de Leave)' },
        { word: 'Met', phonetic: '[met]', trans: 'Conoció / Encontró (Pasado de Meet)' },
        { word: 'Said', phonetic: '[sed]', trans: 'Dijo / Dije (Pasado de Say)' },
        { word: 'Told', phonetic: '[tóuld]', trans: 'Contó / Dijo (Pasado de Tell)' },
        { word: 'Walked', phonetic: '[wuókt]', trans: 'Caminó / Caminé' },
        { word: 'Worked', phonetic: '[wuerkt]', trans: 'Trabajó / Trabajé' },
        { word: 'Studied', phonetic: '[es-tá-did]', trans: 'Estudió / Estudié' },
        { word: 'Played', phonetic: '[pléid]', trans: 'Jugó / Jugué' },
        { word: 'Visited', phonetic: '[ví-si-tid]', trans: 'Visitó / Visité' },
        { word: 'Cleaned', phonetic: '[klínd]', trans: 'Limpió / Limpié' },
        { word: 'Cooked', phonetic: '[kukt]', trans: 'Cocinó / Cociné' },
        { word: 'Started', phonetic: '[estár-tid]', trans: 'Empezó / Empecé' },
        { word: 'Finished', phonetic: '[fí-nish-t]', trans: 'Terminó / Terminé' },
        { word: 'Watched', phonetic: '[uótcht]', trans: 'Miró / Miré' },
        { word: 'Listened', phonetic: '[lís-nd]', trans: 'Escuchó / Escuché' },
        { word: 'Travel', phonetic: '[trá-vel]', trans: 'Viajar' },
        { word: 'Arrive', phonetic: '[a-ráiv]', trans: 'Llegar' },
        { word: 'Decide', phonetic: '[di-sáid]', trans: 'Decidir' },
        { word: 'Happen', phonetic: '[já-pen]', trans: 'Ocurrir / Suceder' },
        { word: 'Suddenly', phonetic: '[sá-den-li]', trans: 'De repente' },
        { word: 'Trip', phonetic: '[trip]', trans: 'Viaje' },
        { word: 'Vacation', phonetic: '[vei-kéi-shon]', trans: 'Vacaciones' },
        { word: 'Accident', phonetic: '[ák-si-dent]', trans: 'Accidente' },
        { word: 'Story', phonetic: '[es-tó-ri]', trans: 'Historia / Cuento' },
        { word: 'Memory', phonetic: '[mé-mo-ri]', trans: 'Recuerdo / Memoria' }
      ]
    },
    {
      id: 'a2_past_continuous',
      title: '2. Past Continuous Tense (Pasado Continuo)',
      summary: 'Descripción de acciones progresivas en desarrollo en un punto preciso del pasado.',
      description: 'El Pasado Continuo se utiliza para enfatizar la duración de una acción en el pasado, describir escenas de fondo o indicar una acción continua que fue interrumpida por otra acción en Pasado Simple.',
      grammar: 'Sintaxis:\n- Afirmativo: Sujeto + Was / Were + Verbo con -ing + Complemento.\n (Was para I, He, She, It / Were para You, We, They).\n- Negativo: Sujeto + Was not (wasn\'t) / Were not (weren\'t) + Verbo en -ing.\n- Interrogativo: Was / Were + Sujeto + Verbo en -ing +?\n- Conectores clave: "When" (seguido generalmente de Pasado Simple) y "While" (seguido generalmente de Pasado Continuo).',
      examples: [
        'Acción Progresiva: "I was studying at 8 PM last night."',
        'Interrupción: "They were walking in the park when it started to rain."',
        'Acciones Simultáneas: "While my mother was cooking, my father was reading."',
        'Interrogativo: "What were you doing when I called you?"'
      ],
      vocabulary: [
        { word: 'Was', phonetic: '[wos]', trans: 'Estaba (I, He, She, It)' },
        { word: 'Were', phonetic: '[wuer]', trans: 'Estaban / Estabas (You, We, They)' },
        { word: 'While', phonetic: '[juáil]', trans: 'Mientras' },
        { word: 'When', phonetic: '[juén]', trans: 'Cuando' },
        { word: 'Rain', phonetic: '[réin]', trans: 'Lloviendo / Lluvia' },
        { word: 'Snow', phonetic: '[snóu]', trans: 'Nevando / Nieve' },
        { word: 'Sleeping', phonetic: '[es-lí-ping]', trans: 'Durmiendo' },
        { word: 'Cooking', phonetic: '[kú-king]', trans: 'Cocinando' },
        { word: 'Reading', phonetic: '[rí-ding]', trans: 'Leyendo' },
        { word: 'Driving', phonetic: '[drái-ving]', trans: 'Conduciendo' },
        { word: 'Walking', phonetic: '[wuó-king]', trans: 'Caminando' },
        { word: 'Running', phonetic: '[rá-ning]', trans: 'Corriendo' },
        { word: 'Working', phonetic: '[wúer-king]', trans: 'Trabajando' },
        { word: 'Studying', phonetic: '[es-tá-di-ing]', trans: 'Estudiando' },
        { word: 'Eating', phonetic: '[í-ting]', trans: 'Comiendo' },
        { word: 'Drinking', phonetic: '[drín-king]', trans: 'Bebiendo' },
        { word: 'Watching', phonetic: '[uót-ching]', trans: 'Mirando' },
        { word: 'Listening', phonetic: '[lís-ning]', trans: 'Escuchando' },
        { word: 'Talking', phonetic: '[tó-king]', trans: 'Hablando' },
        { word: 'Calling', phonetic: '[kó-ling]', trans: 'Llamando' },
        { word: 'Waiting', phonetic: '[uéi-ting]', trans: 'Esperando' },
        { word: 'Cleaning', phonetic: '[klí-ning]', trans: 'Limpiando' },
        { word: 'Shopping', phonetic: '[shó-ping]', trans: 'Comprando' },
        { word: 'Playing', phonetic: '[pléi-ing]', trans: 'Jugando' },
        { word: 'Swimming', phonetic: '[esuí-ming]', trans: 'Nadando' },
        { word: 'Singing', phonetic: '[síng-ing]', trans: 'Cantando' },
        { word: 'Dancing', phonetic: '[dán-sing]', trans: 'Bailando' },
        { word: 'Writing', phonetic: '[rái-ting]', trans: 'Escribiendo' },
        { word: 'Fixing', phonetic: '[fík-sing]', trans: 'Reparando' },
        { word: 'Painting', phonetic: '[péin-ting]', trans: 'Pintando' },
        { word: 'Noise', phonetic: '[nóis]', trans: 'Ruido' },
        { word: 'Sound', phonetic: '[sáund]', trans: 'Sonido' },
        { word: 'Phone call', phonetic: '[fóun kol]', trans: 'Llamada telefónica' },
        { word: 'Moment', phonetic: '[móu-ment]', trans: 'Momento' },
        { word: 'Background', phonetic: '[bák-graund]', trans: 'Fondo / Antecedente' },
        { word: 'At that time', phonetic: '[at dat táim]', trans: 'En ese momento' },
        { word: 'All night', phonetic: '[ol náit]', trans: 'Toda la noche' },
        { word: 'All day', phonetic: '[ol déi]', trans: 'Todo el día' },
        { word: 'Interruption', phonetic: '[in-te-ráp-shon]', trans: 'Interrupción' },
        { word: 'Suddenly', phonetic: '[sá-den-li]', trans: 'De repente' },
        { word: 'Ring', phonetic: '[ring]', trans: 'Sonar (Teléfono/Timbre)' },
        { word: 'Knock', phonetic: '[nok]', trans: 'Tocar la puerta' },
        { word: 'Fall', phonetic: '[fol]', trans: 'Caer' },
        { word: 'Break', phonetic: '[bréik]', trans: 'Romper' },
        { word: 'Lose', phonetic: '[lúz]', trans: 'Perder' },
        { word: 'Find', phonetic: '[fáind]', trans: 'Encontrar' },
        { word: 'Shout', phonetic: '[sháut]', trans: 'Gritar' },
        { word: 'Cry', phonetic: '[krái]', trans: 'Llorar' },
        { word: 'Laugh', phonetic: '[laf]', trans: 'Reír' },
        { word: 'Smile', phonetic: '[esmail]', trans: 'Sonreír' }
      ]
    },
    {
      id: 'a2_comparatives_superlatives',
      title: '3. Comparatives & Superlatives (Comparativos y Superlativos)',
      summary: 'Técnicas de comparación cualitativa entre dos o más entidades.',
      description: 'Estructuras para contrastar diferencias entre dos objetos (comparativos) o resaltar una entidad por encima de todo su grupo (superlativos), según la longitud silábica de los adjetivos.',
      grammar: 'Reglas Morfológicas:\n1. Adjetivos Cortos (1 sílaba o 2 terminados en -y):\n - Comparativo: Adjetivo + -er + than (faster than, happier than).\n - Superlativo: The + Adjetivo + -est (the fastest, the happiest).\n2. Adjetivos Largos (2 o más sílabas):\n Comparativo: More + Adjetivo + than (more expensive than).\n Superlativo: The most + Adjetivo (the most expensive).\n3. Formas Irregulares:\n Good -> Better than -> The best.\n - Bad -> Worse than -> The worst.\n - Far -> Farther/Further than -> The farthest/furthest.',
      examples: [
        'Comparativo Corto: "A plane is faster than a train."',
        'Comparativo Largo: "This book is more interesting than the movie."',
        'Superlativo Corto: "Mount Everest is the highest mountain in the world."',
        'Superlativo Irregular: "That was the worst experience of my life."'
      ],
      vocabulary: [
        { word: 'Fast', phonetic: '[fast]', trans: 'Rápido' },
        { word: 'Faster', phonetic: '[fás-ter]', trans: 'Más rápido' },
        { word: 'Fastest', phonetic: '[fás-test]', trans: 'El más rápido' },
        { word: 'Slow', phonetic: '[slóu]', trans: 'Lento' },
        { word: 'Slower', phonetic: '[slóu-er]', trans: 'Más lento' },
        { word: 'Slowest', phonetic: '[slóu-est]', trans: 'El más lento' },
        { word: 'Big', phonetic: '[big]', trans: 'Grande' },
        { word: 'Bigger', phonetic: '[bí-ger]', trans: 'Más grande' },
        { word: 'Biggest', phonetic: '[bí-gest]', trans: 'El más grande' },
        { word: 'Small', phonetic: '[smol]', trans: 'Pequeño' },
        { word: 'Smaller', phonetic: '[smó-ler]', trans: 'Más pequeño' },
        { word: 'Smallest', phonetic: '[smó-lest]', trans: 'El más pequeño' },
        { word: 'Tall', phonetic: '[tol]', trans: 'Alto' },
        { word: 'Taller', phonetic: '[tó-ler]', trans: 'Más alto' },
        { word: 'Tallest', phonetic: '[tó-lest]', trans: 'El más alto' },
        { word: 'Short', phonetic: '[short]', trans: 'Bajo / Corto' },
        { word: 'Shorter', phonetic: '[shór-ter]', trans: 'Más bajo / corto' },
        { word: 'Shortest', phonetic: '[shór-test]', trans: 'El más bajo / corto' },
        { word: 'Cheap', phonetic: '[chíp]', trans: 'Barato' },
        { word: 'Cheaper', phonetic: '[chí-per]', trans: 'Más barato' },
        { word: 'Cheapest', phonetic: '[chí-pest]', trans: 'El más barato' },
        { word: 'Expensive', phonetic: '[eks-pén-siv]', trans: 'Costoso / Caro' },
        { word: 'More expensive', phonetic: '[mor eks-pén-siv]', trans: 'Más costoso' },
        { word: 'Most expensive', phonetic: '[móust eks-pén-siv]', trans: 'El más costoso' },
        { word: 'Good', phonetic: '[gud]', trans: 'Bueno' },
        { word: 'Better', phonetic: '[bé-ter]', trans: 'Mejor' },
        { word: 'Best', phonetic: '[best]', trans: 'El mejor' },
        { word: 'Bad', phonetic: '[bad]', trans: 'Malo' },
        { word: 'Worse', phonetic: '[wers]', trans: 'Peor' },
        { word: 'Worst', phonetic: '[werst]', trans: 'El peor' },
        { word: 'Far', phonetic: '[far]', trans: 'Lejos' },
        { word: 'Further', phonetic: '[fér-der]', trans: 'Más lejos' },
        { word: 'Furthest', phonetic: '[fér-dest]', trans: 'El más lejano' },
        { word: 'Easy', phonetic: '[í-zi]', trans: 'Fácil' },
        { word: 'Easier', phonetic: '[í-zi-er]', trans: 'Más fácil' },
        { word: 'Easiest', phonetic: '[í-zi-est]', trans: 'El más fácil' },
        { word: 'Difficult', phonetic: '[dí-fi-kult]', trans: 'Difícil' },
        { word: 'More difficult', phonetic: '[mor dí-fi-kult]', trans: 'Más difícil' },
        { word: 'Most difficult', phonetic: '[móust dí-fi-kult]', trans: 'El más difícil' },
        { word: 'Hot', phonetic: '[jot]', trans: 'Caluroso / Caliente' },
        { word: 'Hotter', phonetic: '[jó-ter]', trans: 'Más caluroso' },
        { word: 'Hottest', phonetic: '[jó-test]', trans: 'El más caluroso' },
        { word: 'Cold', phonetic: '[kóuld]', trans: 'Frío' },
        { word: 'Colder', phonetic: '[kóul-der]', trans: 'Más frío' },
        { word: 'Coldest', phonetic: '[kóul-dest]', trans: 'El más frío' },
        { word: 'Beautiful', phonetic: '[biú-ti-ful]', trans: 'Hermoso' },
        { word: 'More beautiful', phonetic: '[mor biú-ti-ful]', trans: 'Más hermoso' },
        { word: 'Most beautiful', phonetic: '[móust biú-ti-ful]', trans: 'El más hermoso' },
        { word: 'Than', phonetic: '[dan]', trans: 'Que (en comparaciones)' },
        { word: 'World', phonetic: '[wuerld]', trans: 'Mundo' }
      ]
    },
    {
      id: 'a2_modals',
      title: '4. Modal Verbs: Can, Could, Must, Should, May (Verbos Modales)',
      summary: 'Expresión formal de habilidad, permiso, posibilidad, obligación y consejo.',
      description: 'Los verbos modales son auxiliares especiales que modifican el significado del verbo principal. No cambian de forma según el sujeto (no llevan "-s" en 3ra persona) y van seguidos directamente de un verbo en su forma base (sin "to").',
      grammar: 'Sintaxis y Usos:\n- Can: Habilidad en presente o permiso informal. (Sujeto + Can + Verbo Base).\n- Could: Habilidad en pasado o petición formal educada. (Sujeto + Could + Verbo Base).\n- Should: Recomendaciones o consejos. (Sujeto + Should + Verbo Base).\n- Must: Obligación fuerte o necesidad absoluta. (Sujeto + Must + Verbo Base).\n- May / Might: Posibilidad futura o permiso muy formal.',
      examples: [
        'Habilidad: "She can speak three languages fluently."',
        'Consejo: "You look tired; you should go to bed early."',
        'Obligación: "Students must wear a uniform at school."',
        'Permiso Formal: "May I use your bathroom, please?"'
      ],
      vocabulary: [
        { word: 'Can', phonetic: '[kan]', trans: 'Poder (Capacidad / Permiso)' },
        { word: 'Cannot / Can\'t', phonetic: '[ká-not / kant]', trans: 'No poder' },
        { word: 'Could', phonetic: '[kud]', trans: 'Podría / Podía' },
        { word: 'Couldn\'t', phonetic: '[kúd-nt]', trans: 'No podía / No podría' },
        { word: 'Should', phonetic: '[shud]', trans: 'Debería (Consejo)' },
        { word: 'Shouldn\'t', phonetic: '[shúd-nt]', trans: 'No debería' },
        { word: 'Must', phonetic: '[mast]', trans: 'Deber (Obligación)' },
        { word: 'Must not / Mustn\'t', phonetic: '[mást-nt]', trans: 'Prohibición absoluta' },
        { word: 'May', phonetic: '[méi]', trans: 'Poder (Permiso formal / Posibilidad)' },
        { word: 'Might', phonetic: '[máit]', trans: 'Podría (Posibilidad remota)' },
        { word: 'Permission', phonetic: '[per-mí-shon]', trans: 'Permiso' },
        { word: 'Ability', phonetic: '[a-bí-li-ti]', trans: 'Habilidad / Capacidad' },
        { word: 'Advice', phonetic: '[ad-váis]', trans: 'Consejo' },
        { word: 'Obligation', phonetic: '[ob-li-géi-shon]', trans: 'Obligación' },
        { word: 'Prohibition', phonetic: '[pro-ji-bí-shon]', trans: 'Prohibición' },
        { word: 'Possibility', phonetic: '[po-sa-bí-li-ti]', trans: 'Posibilidad' },
        { word: 'Rule', phonetic: '[rúl]', trans: 'Regla' },
        { word: 'Law', phonetic: '[ló]', trans: 'Ley' },
        { word: 'Swim', phonetic: '[esuím]', trans: 'Nadar' },
        { word: 'Fly', phonetic: '[flái]', trans: 'Volar' },
        { word: 'Drive', phonetic: '[dráiv]', trans: 'Conducir' },
        { word: 'Speak', phonetic: '[es-pík]', trans: 'Hablar' },
        { word: 'Help', phonetic: '[jelp]', trans: 'Ayudar' },
        { word: 'Borrow', phonetic: '[bó-rou]', trans: 'Tomar prestado' },
        { word: 'Lend', phonetic: '[lend]', trans: 'Prestar' },
        { word: 'Wear', phonetic: '[uér]', trans: 'Llevar puesto / Usar ropa' },
        { word: 'Seatbelt', phonetic: '[sít-belt]', trans: 'Cinturón de seguridad' },
        { word: 'Helmet', phonetic: '[jél-met]', trans: 'Casco' },
        { word: 'Quiet', phonetic: '[kuái-et]', trans: 'Callado / Silencioso' },
        { word: 'Smoke', phonetic: '[esmóuk]', trans: 'Fumar / Humo' },
        { word: 'Park', phonetic: '[park]', trans: 'Estacionar' },
        { word: 'Enter', phonetic: '[én-ter]', trans: 'Entrar' },
        { word: 'Leave', phonetic: '[lív]', trans: 'Salir / Dejar' },
        { word: 'Doctor', phonetic: '[dók-tor]', trans: 'Médico' },
        { word: 'Medicine', phonetic: '[mé-di-sin]', trans: 'Medicina' },
        { word: 'Rest', phonetic: '[rest]', trans: 'Descanso / Descansar' },
        { word: 'Exercise', phonetic: '[ék-ser-sais]', trans: 'Ejercicio / Ejercitarse' },
        { word: 'Water', phonetic: '[uó-ter]', trans: 'Agua' },
        { word: 'Passport', phonetic: '[pás-port]', trans: 'Pasaporte' },
        { word: 'Ticket', phonetic: '[tí-ket]', trans: 'Boleto / Ticket' },
        { word: 'Polite', phonetic: '[po-láit]', trans: 'Educado / Amable' },
        { word: 'Rude', phonetic: '[rúd]', trans: 'Grosero / Mal educado' },
        { word: 'Possible', phonetic: '[pó-si-bl]', trans: 'Posible' },
        { word: 'Impossible', phonetic: '[im-pó-si-bl]', trans: 'Imposible' },
        { word: 'Necessary', phonetic: '[né-se-se-ri]', trans: 'Necesario' },
        { word: 'Important', phonetic: '[im-pór-tant]', trans: 'Importante' },
        { word: 'Danger', phonetic: '[déin-dzher]', trans: 'Peligro' },
        { word: 'Safe', phonetic: '[séif]', trans: 'Seguro' },
        { word: 'Careful', phonetic: '[kér-ful]', trans: 'Cuidadoso' },
        { word: 'Quickly', phonetic: '[kuík-li]', trans: 'Rápidamente' }
      ]
    },
    {
      id: 'a2_future_forms',
      title: '5. Future Structures: Will vs. Be Going To (Estructuras de Futuro)',
      summary: 'Diferenciación técnica entre predicciones, decisiones espontáneas y planes preconcebidos.',
      description: 'Uso correcto de los dos esquemas del futuro simple en inglés. "Be going to" se utiliza para planes ya establecidos e intenciones previas, mientras que "Will" se emplea para decisiones tomadas al instante, promesas y predicciones sin evidencia inmediata.',
      grammar: 'Estructuras Comparativas:\n1. Be Going To (Planes / Intenciones / Evidencia directa):\n - Sujeto + am/is/are + going to + Verbo Base.\n - Ejemplo: "I am going to study medicine next year" (Plan ya decidido). \n2. Will (Decisiones espontáneas / Promesas / Predicciones sin evidencia):\n - Sujeto + Will + Verbo Base. (Negativo: Won\'t).\n Ejemplo: "The phone is ringing. I will answer it" (Decisión al instante).',
      examples: [
        'Plan Previo: "They are going to buy a house next month."',
        'Decisión Espontánea: "I am tired. I think I will go to sleep now."',
        'Predicción basada en evidencia: "Look at those dark clouds! It is going to rain."',
        'Promesa: "Don\'t worry, I will help you with your homework."'
      ],
      vocabulary: [
        { word: 'Will', phonetic: '[uil]', trans: 'Auxiliar de futuro' },
        { word: 'Won\'t', phonetic: '[wóunt]', trans: 'Will not (Negación futura)' },
        { word: 'Going to', phonetic: '[góu-ing tu]', trans: 'Ir a (Intención/Plan)' },
        { word: 'Tomorrow', phonetic: '[tu-mó-rou]', trans: 'Mañana' },
        { word: 'Next week', phonetic: '[nekst uík]', trans: 'La próxima semana' },
        { word: 'Next month', phonetic: '[nekst month]', trans: 'El próximo mes' },
        { word: 'Next year', phonetic: '[nekst iér]', trans: 'El próximo año' },
        { word: 'Soon', phonetic: '[sún]', trans: 'Pronto' },
        { word: 'Later', phonetic: '[léi-ter]', trans: 'Más tarde' },
        { word: 'In the future', phonetic: '[in de fiú-tchur]', trans: 'En el futuro' },
        { word: 'Plan', phonetic: '[plan]', trans: 'Plan / Planificar' },
        { word: 'Intention', phonetic: '[in-tén-shon]', trans: 'Intención' },
        { word: 'Decision', phonetic: '[di-sí-zhon]', trans: 'Decisión' },
        { word: 'Prediction', phonetic: '[pri-dík-shon]', trans: 'Predicción' },
        { word: 'Promise', phonetic: '[pró-mis]', trans: 'Promesa / Prometer' },
        { word: 'Offer', phonetic: '[ó-fer]', trans: 'Ofrecer / Oferta' },
        { word: 'Spontaneous', phonetic: '[es-pon-téi-ni-os]', trans: 'Espontáneo' },
        { word: 'Evidence', phonetic: '[é-vi-dens]', trans: 'Evidencia' },
        { word: 'Cloud', phonetic: '[kláud]', trans: 'Nube' },
        { word: 'Rain', phonetic: '[réin]', trans: 'Llover' },
        { word: 'Travel', phonetic: '[trá-vel]', trans: 'Viajar' },
        { word: 'Fly', phonetic: '[flái]', trans: 'Volar' },
        { word: 'Move', phonetic: '[múv]', trans: 'Mudarse / Moverse' },
        { word: 'Start', phonetic: '[estárt]', trans: 'Empezar' },
        { word: 'Finish', phonetic: '[fí-nish]', trans: 'Terminar' },
        { word: 'Graduate', phonetic: '[grá-diu-eit]', trans: 'Graduarse' },
        { word: 'Job', phonetic: '[dzhob]', trans: 'Trabajo' },
        { word: 'Career', phonetic: '[ka-ríer]', trans: 'Carrera profesional' },
        { word: 'University', phonetic: '[iu-ni-vér-si-ti]', trans: 'Universidad' },
        { word: 'Wedding', phonetic: '[ué-ding]', trans: 'Boda' },
        { word: 'Party', phonetic: '[pár-ti]', trans: 'Fiesta' },
        { word: 'Meeting', phonetic: '[mí-ting]', trans: 'Reunión' },
        { word: 'Flight', phonetic: '[fláit]', trans: 'Vuelo' },
        { word: 'Hotel', phonetic: '[jou-tél]', trans: 'Hotel' },
        { word: 'Ticket', phonetic: '[tí-ket]', trans: 'Boleto' },
        { word: 'Reservation', phonetic: '[re-zer-véi-shon]', trans: 'Reservación' },
        { word: 'Think', phonetic: '[think]', trans: 'Pensar / Creer' },
        { word: 'Believe', phonetic: '[bi-lív]', trans: 'Creer' },
        { word: 'Hope', phonetic: '[jóup]', trans: 'Esperar (Deseo)' },
        { word: 'Expect', phonetic: '[eks-pékt]', trans: 'Esperar (Expectativa)' },
        { word: 'Maybe', phonetic: '[méi-bi]', trans: 'Tal vez' },
        { word: 'Perhaps', phonetic: '[per-jáps]', trans: 'Quizás' },
        { word: 'Probably', phonetic: '[pró-ba-bli]', trans: 'Probablemente' },
        { word: 'Definitely', phonetic: '[dé-fi-nit-li]', trans: 'Definitivamente' },
        { word: 'Sure', phonetic: '[shur]', trans: 'Seguro' },
        { word: 'Certain', phonetic: '[sér-ten]', trans: 'Cierto / Seguro' },
        { word: 'Agree', phonetic: '[a-grí]', trans: 'Estar de acuerdo' },
        { word: 'Refuse', phonetic: '[ri-fiúz]', trans: 'Rechazar' },
        { word: 'Help', phonetic: '[jelp]', trans: 'Ayudar' },
        { word: 'Carry', phonetic: '[ká-ri]', trans: 'Llevar / Cargar' }
      ]
    }
  ],
  'B1': [
    {
      id: 'b1_present_perfect',
      title: '1. Present Perfect Simple & Continuous (Presente Perfecto Simple y Continuo)',
      summary: 'Vinculación de acciones pasadas con el momento presente y su duración o impacto actual.',
      description: 'El Presente Perfecto conecta acontecimientos pasados con la situación presente. Se utiliza para experiencias de vida sin marco temporal específico, acciones completadas recientemente con impacto actual, o situaciones que iniciaron en el pasado y continúan vigentes. El Presente Perfecto Continuo enfatiza la duración ininterrumpida de la acción.',
      grammar: 'Sintaxis y Parámetros Técnicos:\n1. Present Perfect Simple:\n Estrutura: Sujeto + Have / Has + Verbo en Pasado Participio (3ra columna).\n Adverbios clave: Already (ya - afirmativo), Yet (aún/ya- negativo/pregunta), Just (acabar de), Ever (alguna vez), Never (nunca).\n2. Present Perfect Continuous:\n - Estructura: Sujeto + Have / Has + been + Verbo con -ing.\nUso: Enfatiza la continuidad temporal (ej. "I have been studying for 3 hours").\n3. For vs. Since:\n - "For": Utilizado para indicar una duración de tiempo (for 5 years, for two hours). \n "Since": Utilizado para marcar el punto de inicio de una acción (since 2010, since 8 AM).',
      examples: [
        'Experiencia de Vida: "I have visited Japan twice, but I have never seen Mount Fuji."',
        'Acción Reciente: "She has just finished her university thesis."',
        'Duración desde el Pasado: "We have lived in this city since 2018."',
        'Énfasis en el Proceso: "He has been working on that software project all morning."'
      ],
      vocabulary: [

        { word: 'Experience', phonetic: '[eks-pí-ri-ens]', trans: 'Experiencia' },
        { word: 'Achievement', phonetic: '[a-chív-ment]', trans: 'Logro' },
        { word: 'Lifetime', phonetic: '[láif-taim]', trans: 'Toda la vida' },
        { word: 'Duration', phonetic: '[diu-réi-shon]', trans: 'Duración' },
        { word: 'Period', phonetic: '[pí-ri-od]', trans: 'Período' },
        { word: 'Career', phonetic: '[ka-ríer]', trans: 'Carrera' },
        { word: 'Progress', phonetic: '[pró-gres]', trans: 'Progreso' },
        { word: 'Result', phonetic: '[ri-zált]', trans: 'Resultado' },
        { word: 'Impact', phonetic: '[ím-pakt]', trans: 'Impacto' },
        { word: 'Effect', phonetic: '[i-fékt]', trans: 'Efecto' },
        { word: 'Change', phonetic: '[chéindzh]', trans: 'Cambio' },
        { word: 'Improvement', phonetic: '[im-prúv-ment]', trans: 'Mejora' },
        { word: 'Project', phonetic: '[pró-dzhekt]', trans: 'Proyecto' },
        { word: 'Goal', phonetic: '[góul]', trans: 'Meta / Objetivo' },
        { word: 'Success', phonetic: '[sak-sés]', trans: 'Éxito' },
        { word: 'Failure', phonetic: '[féi-liur]', trans: 'Fallo / Fracaso' },
        { word: 'Opportunity', phonetic: '[o-por-tiú-ni-ti]', trans: 'Oportunidad' },
        { word: 'Challenge', phonetic: '[chá-lendzh]', trans: 'Desafío' },
        { word: 'Degree', phonetic: '[di-grí]', trans: 'Título universitario / Grado' },
        { word: 'Skill', phonetic: '[es-kil]', trans: 'Habilidad' },
        { word: 'Knowledge', phonetic: '[nó-ledzh]', trans: 'Conocimiento' },
        { word: 'Research', phonetic: '[ri-sértch]', trans: 'Investigación' },
        { word: 'Development', phonetic: '[di-vé-lop-ment]', trans: 'Desarrollo' },
        { word: 'Effort', phonetic: '[é-fort]', trans: 'Esfuerzo' },
        { word: 'Task', phonetic: '[task]', trans: 'Tarea / Labor' },
        { word: 'Assignment', phonetic: '[a-sáin-ment]', trans: 'Asignación' },
        { word: 'Process', phonetic: '[pró-ses]', trans: 'Proceso' },
        { word: 'Evidence', phonetic: '[é-vi-dens]', trans: 'Evidencia' },
        { word: 'Proof', phonetic: '[prúf]', trans: 'Prueba' },
        { word: 'Detail', phonetic: '[di-téil]', trans: 'Detalle' },
        { word: 'Situation', phonetic: '[si-tchu-éi-shon]', trans: 'Situación' },
        { word: 'Condition', phonetic: '[kon-dí-shon]', trans: 'Condición' },
        { word: 'Status', phonetic: '[está-tus]', trans: 'Estado / Estatus' },
        { word: 'Phase', phonetic: '[féiz]', trans: 'Fase / Etapa' },
        { word: 'Stage', phonetic: '[estéidzh]', trans: 'Etapa / Escenario' },
        { word: 'Background', phonetic: '[bák-graund]', trans: 'Antecedentes / Trasfondo' },
        { word: 'History', phonetic: '[jís-to-ri]', trans: 'Historia' },
        { word: 'Timeline', phonetic: '[táim-lain]', trans: 'Cronología' },
        { word: 'Momentum', phonetic: '[mo-mén-tum]', trans: 'Impulso' },
        { word: 'Milestone', phonetic: '[máil-stoun]', trans: 'Hito / Logro importante' },

        { word: 'Accomplish', phonetic: '[a-kóm-plish]', trans: 'Lograr/Cumplir' },
        { word: 'Achieve', phonetic: '[a-chív]', trans: 'Alcanzar / Conseguir' },
        { word: 'Complete', phonetic: '[kom-plít]', trans: 'Completar' },
        { word: 'Finish', phonetic: '[fí-nish]', trans: 'Terminar' },
        { word: 'Develop', phonetic: '[di-vé-lop]', trans: 'Desarrollar' },
        { word: 'Improve', phonetic: '[im-prúv]', trans: 'Mejorar' },
        { word: 'Increase', phonetic: '[in-krís]', trans: 'Aumentar' },
        { word: 'Decrease', phonetic: '[di-krís]', trans: 'Disminuir' },
        { word: 'Change', phonetic: '[chéindzh]', trans: 'Cambiar' },
        { word: 'Transform', phonetic: '[trans-fórm]', trans: 'Transformar' },
        { word: 'Discover', phonetic: '[dis-kó-ver]', trans: 'Descubrir' },
        { word: 'Create', phonetic: '[kri-éit]', trans: 'Crear' },
        { word: 'Design', phonetic: '[di-záin]', trans: 'Diseñar' },
        { word: 'Build', phonetic: '[bild]', trans: 'Construir' },
        { word: 'Establish', phonetic: '[es-tá-blish]', trans: 'Establecer' },
        { word: 'Publish', phonetic: '[pá-blish]', trans: 'Publicar' },
        { word: 'Release', phonetic: '[ri-lís]', trans: 'Lanzar / Liberar' },
        { word: 'Launch', phonetic: '[lonch]', trans: 'Lanzar' },
        { word: 'Maintain', phonetic: '[mein-téin]', trans: 'Mantener' },
        { word: 'Sustain', phonetic: '[sas-téin]', trans: 'Sostener' },
        { word: 'Continue', phonetic: '[kon-tí-niu]', trans: 'Continuar' },
        { word: 'Remain', phonetic: '[ri-méin]', trans: 'Permanecer' },
        { word: 'Exist', phonetic: '[eg-zíst]', trans: 'Existir' },
        { word: 'Experience', phonetic: '[eks-pí-ri-ens]', trans: 'Experimentar' },
        { word: 'Suffer', phonetic: '[sá-fer]', trans: 'Sufrir' },
        { word: 'Gain', phonetic: '[géin]', trans: 'Ganar / Obtener' },
        { word: 'Lose', phonetic: '[lúz]', trans: 'Perder' },
        { word: 'Find', phonetic: '[fáind]', trans: 'Encontrar' },
        { word: 'Collect', phonetic: '[ko-lékt]', trans: 'Recolectar' },
        { word: 'Gather', phonetic: '[gá-der]', trans: 'Reunir' },
        { word: 'Organize', phonetic: '[ór-ga-naiz]', trans: 'Organizar' },
        { word: 'Prepare', phonetic: '[pri-pér]', trans: 'Preparar' },
        { word: 'Manage', phonetic: '[má-nidzh]', trans: 'Gestionar / Dirigir' },
        { word: 'Lead', phonetic: '[líd]', trans: 'Liderar' },
        { word: 'Coordinate', phonetic: '[kou-ór-di-neit]', trans: 'Coordinar' },
        { word: 'Supervise', phonetic: '[sú-per-vais]', trans: 'Supervisar' },
        { word: 'Evaluate', phonetic: '[i-vá-liu-eit]', trans: 'Evaluar' },
        { word: 'Assess', phonetic: '[a-sés]', trans: 'Evaluar / Valorar' },
        { word: 'Verify', phonetic: '[vé-ri-fai]', trans: 'Verificar' },
        { word: 'Confirm', phonetic: '[kon-férm]', trans: 'Confirmar' },
        { word: 'Demonstrate', phonetic: '[dé-mons-treit]', trans: 'Demostrar' },
        { word: 'Prove', phonetic: '[prúv]', trans: 'Probar / Demostrar' },
        { word: 'Notice', phonetic: '[nó-tis]', trans: 'Notar / Percibir' },
        { word: 'Realize', phonetic: '[rí-a-laiz]', trans: 'Darse cuenta' },
        { word: 'Recognize', phonetic: '[ré-kog-naiz]', trans: 'Reconocer' },
        { word: 'Adapt', phonetic: '[a-dápt]', trans: 'Adaptar' },
        { word: 'Adjust', phonetic: '[a-dzhást]', trans: 'Ajustar' },
        { word: 'Expand', phonetic: '[eks-pánd]', trans: 'Expandir' },
        { word: 'Extend', phonetic: '[eks-ténd]', trans: 'Extender' },
        { word: 'Reduce', phonetic: '[ri-diús]', trans: 'Reducir' },

        { word: 'Recent', phonetic: '[rí-sent]', trans: 'Reciente' },
        { word: 'Continuous', phonetic: '[kon-tí-niu-os]', trans: 'Continuo' },
        { word: 'Ongoing', phonetic: '[ón-gou-ing]', trans: 'En curso' },
        { word: 'Constant', phonetic: '[kón-stant]', trans: 'Constante' },
        { word: 'Frequent', phonetic: '[frí-kuent]', trans: 'Frecuente' },
        { word: 'Rare', phonetic: '[rér]', trans: 'Raro / Poco común' },
        { word: 'Unusual', phonetic: '[an-iú-zhual]', trans: 'Inusual' },
        { word: 'Significant', phonetic: '[sig-ní-fi-kant]', trans: 'Significativo' },
        { word: 'Noticeable', phonetic: '[nó-tis-a-bl]', trans: 'Notable' },
        { word: 'Remarkable', phonetic: '[ri-már-ka-bl]', trans: 'Extraordinario' },
        { word: 'Successful', phonetic: '[sak-sés-ful]', trans: 'Exitoso' },
        { word: 'Unsuccessful', phonetic: '[an-sak-sés-ful]', trans: 'Infructuoso' },
        { word: 'Effective', phonetic: '[i-fék-tiv]', trans: 'Efectivo' },
        { word: 'Efficient', phonetic: '[i-fí-shent]', trans: 'Eficiente' },
        { word: 'Active', phonetic: '[ák-tiv]', trans: 'Activo' },
        { word: 'Passive', phonetic: '[pá-siv]', trans: 'Pasivo' },
        { word: 'Temporary', phonetic: '[tém-po-ra-ri]', trans: 'Temporal' },
        { word: 'Permanent', phonetic: '[pér-ma-nent]', trans: 'Permanente' },
        { word: 'Accumulated', phonetic: '[a-kiú-miu-lei-tid]', trans: 'Acumulado' },
        { word: 'Experienced', phonetic: '[eks-pí-ri-enst]', trans: 'Experimentado' },
        { word: 'Skilled', phonetic: '[eskild]', trans: 'Habilidoso' },
        { word: 'Qualified', phonetic: '[kuó-li-faid]', trans: 'Cualificado' },
        { word: 'Unfinished', phonetic: '[an-fí-nisht]', trans: 'Inconcluso' },
        { word: 'Complete', phonetic: '[kom-plít]', trans: 'Completo' },
        { word: 'Incomplete', phonetic: '[in-kom-plít]', trans: 'Incompleto' },
        { word: 'Visible', phonetic: '[ví-zi-bl]', trans: 'Visible' },
        { word: 'Invisible', phonetic: '[in-ví-zi-bl]', trans: 'Invisible' },
        { word: 'Relevant', phonetic: '[ré-le-vant]', trans: 'Relevante' },
        { word: 'Irrelevant', phonetic: '[i-ré-le-vant]', trans: 'Irrelevante' },
        { word: 'Valuable', phonetic: '[vá-liu-a-bl]', trans: 'Valioso' },
        { word: 'Priceless', phonetic: '[práis-les]', trans: 'Invaluable' },
        { word: 'Worthless', phonetic: '[wérth-les]', trans: 'Sin valor' },
        { word: 'Sufficient', phonetic: '[sa-fí-shent]', trans: 'Suficiente' },
        { word: 'Insufficient', phonetic: '[in-sa-fí-shent]', trans: 'Insuficiente' },
        { word: 'Extensive', phonetic: '[eks-tén-siv]', trans: 'Extenso' },
        { word: 'Limited', phonetic: '[lí-mi-tid]', trans: 'Limitado' },
        { word: 'Current', phonetic: '[ká-rent]', trans: 'Actual' },
        { word: 'Present', phonetic: '[pré-zent]', trans: 'Presente' },
        { word: 'Initial', phonetic: '[i-ní-shal]', trans: 'Inicial' },
        { word: 'Final', phonetic: '[fái-nal]', trans: 'Final' },

        { word: 'Already', phonetic: '[ol-ré-di]', trans: 'Ya (en oraciones afirmativas)' },
        { word: 'Yet', phonetic: '[yet]', trans: 'Aún / Ya (negativas/preguntas)' },
        { word: 'Just', phonetic: '[dzhast]', trans: 'Acabar de / Justo' },
        { word: 'Ever', phonetic: '[é-ver]', trans: 'Alguna vez' },
        { word: 'Never', phonetic: '[né-ver]', trans: 'Nunca' },
        { word: 'For', phonetic: '[for]', trans: 'Durante (período de tiempo)' },
        { word: 'Since', phonetic: '[sins]', trans: 'Desde (punto en el tiempo)' },
        { word: 'Recently', phonetic: '[rí-sent-li]', trans: 'Recientemente' },
        { word: 'Lately', phonetic: '[léit-li]', trans: 'Últimamente' },
        { word: 'So far', phonetic: '[sóu far]', trans: 'Hasta ahora' },
        { word: 'Up to now', phonetic: '[ap tu náu]', trans: 'Hasta este momento' },
        { word: 'Until now', phonetic: '[an-tíl náu]', trans: 'Hasta ahora' },
        { word: 'How long', phonetic: '[jáu long]', trans: 'Cuánto tiempo' },
        { word: 'All morning', phonetic: '[ol mór-ning]', trans: 'Toda la mañana' },
        { word: 'All day', phonetic: '[ol déi]', trans: 'Todo el día' },
        { word: 'For a long time', phonetic: '[for a long táim]', trans: 'Por mucho tiempo' },
        { word: 'For ages', phonetic: '[for éi-dzjiz]', trans: 'Por siglos / Por mucho tiempo' },
        { word: 'In recent years', phonetic: '[in rí-sent iérs]', trans: 'En años recientes' },
        { word: 'Several times', phonetic: '[sé-ve-ral taims]', trans: 'Varias veces' },
        { word: 'Many times', phonetic: '[mé-ni taims]', trans: 'Muchas veces' },
        { word: 'Once', phonetic: '[wans]', trans: 'Una vez' },
        { word: 'Twice', phonetic: '[tuáis]', trans: 'Dos veces' },
        { word: 'Three times', phonetic: '[thrí taims]', trans: 'Tres veces' },
        { word: 'Over the years', phonetic: '[óu-ver de iérs]', trans: 'A lo largo de los años' },
        { word: 'As of late', phonetic: '[az ov léit]', trans: 'Últimamente' },
        { word: 'To date', phonetic: '[tu déit]', trans: 'Hasta la fecha' },
        { word: 'In the meantime', phonetic: '[in de mín-taim]', trans: 'Mientras tanto' },
        { word: 'Sooner or later', phonetic: '[sú-ner or léi-ter]', trans: 'Tarde o temprano' },
        { word: 'From time to time', phonetic: '[from táim tu táim]', trans: 'De vez en cuando' },
        { word: 'At last', phonetic: '[at last]', trans: 'Por fin / Al fin' }
      ]
    },
    {
      id: 'b1_conditionals',
      title: '2. Conditionals: First, Second & Zero Conditional (Oraciones Condicionales)',
      summary: 'Formulación de hipótesis, causas, consecuencias reales, futuras y escenarios imaginarios.',
      description: 'Dominio de las estructuras condicionales para expresar relaciones de causa y efecto. El Condicional Cero maneja leyes universales; el Primer Condicional trata sobre situaciones futuras probables; y el Segundo Condicional aborda situaciones hipotéticas o irrestrictas en el presente/futuro.',
      grammar: 'Modelos Estructurales:\n1. Zero Conditional (Causas científicas / Verdades generales):\n - Structure: If + Present Simple, Present Simple.\n Ejemplo: "If you heat ice, it melts." (Si calientas hielo, se derrite). \n2. First Conditional (Planes e hipótesis futuras probables):\n - Structure: If + Present Simple, Will + Verbo Base.\n Ejemplo: "If it rains tomorrow, we will cancel the picnic." (Si llueve mañana, cancelaremos el picnic).\n3. Second Conditional (Situaciones hipotéticas o irremediables en presente):\n - Structure: If + Past Simple, Would + Verbo Base.\n Nota técnica: El verbo To Be utiliza "were" para todos los pronombres (If I were you...).\n Ejemplo: "If I won the lottery, I would buy a house." (Si ganara la lotería, compraría una casa).',
      examples: [
        'Zero Conditional: "If people do not eat, they get weak."',
        'First Conditional: "If you study hard, you will pass the B1 certification exam."',
        'Second Conditional: "If I had more free time, I would learn how to play the piano."',
        'Advice (2nd Cond): "If I were in your position, I would talk to the manager directly."'
      ],
      vocabulary: [

        { word: 'Condition', phonetic: '[kon-dí-shon]', trans: 'Condición' },
        { word: 'Hypothesis', phonetic: '[jai-pó-the-sis]', trans: 'Hipótesis' },
        { word: 'Possibility', phonetic: '[po-sa-bí-li-ti]', trans: 'Posibilidad' },
        { word: 'Consequence', phonetic: '[kón-se-kuens]', trans: 'Consecuencia' },
        { word: 'Outcome', phonetic: '[aut-kom]', trans: 'Resultado / Eventualidad' },
        { word: 'Scenario', phonetic: '[se-ná-ri-ou]', trans: 'Escenario' },
        { word: 'Alternative', phonetic: '[ol-tér-na-tiv]', trans: 'Alternativa' },
        { word: 'Choice', phonetic: '[chois]', trans: 'Elección' },
        { word: 'Option', phonetic: '[óp-shon]', trans: 'Opción' },
        { word: 'Decision', phonetic: '[di-sí-zhon]', trans: 'Decisión' },
        { word: 'Risk', phonetic: '[risk]', trans: 'Riesgo' },
        { word: 'Benefit', phonetic: '[bé-ne-fit]', trans: 'Beneficio' },
        { word: 'Advantage', phonetic: '[ad-ván-tidzh]', trans: 'Ventaja' },
        { word: 'Disadvantage', phonetic: '[dis-ad-ván-tidzh]', trans: 'Desventaja' },
        { word: 'Lottery', phonetic: '[ló-te-ri]', trans: 'Lotería' },
        { word: 'Fortune', phonetic: '[fór-tchun]', trans: 'Fortuna' },
        { word: 'Wealth', phonetic: '[uelth]', trans: 'Riqueza' },
        { word: 'Dream', phonetic: '[drím]', trans: 'Sueño' },
        { word: 'Wish', phonetic: '[uish]', trans: 'Deseo' },
        { word: 'Reality', phonetic: '[ri-á-li-ti]', trans: 'Realidad' },
        { word: 'Imagination', phonetic: '[i-ma-dzhi-néi-shon]', trans: 'Imaginación' },
        { word: 'Fact', phonetic: '[fakt]', trans: 'Hecho' },
        { word: 'Truth', phonetic: '[truth]', trans: 'Verdad' },
        { word: 'Theory', phonetic: '[thí-o-ri]', trans: 'Teoría' },
        { word: 'Law of nature', phonetic: '[lo ov néi-tchur]', trans: 'Ley de la naturaleza' },
        { word: 'Temperature', phonetic: '[tém-pre-tchur]', trans: 'Temperatura' },
        { word: 'Ice', phonetic: '[áis]', trans: 'Hielo' },
        { word: 'Heat', phonetic: '[jít]', trans: 'Calor' },
        { word: 'Fire', phonetic: '[fái-er]', trans: 'Fuego' },
        { word: 'Water', phonetic: '[uó-ter]', trans: 'Agua' },
        { word: 'Steam', phonetic: '[estím]', trans: 'Vapor' },
        { word: 'Pressure', phonetic: '[pré-shur]', trans: 'Presión' },
        { word: 'Solution', phonetic: '[so-lú-shon]', trans: 'Solución' },
        { word: 'Problem', phonetic: '[pró-blem]', trans: 'Problema' },
        { word: 'Dilemma', phonetic: '[di-lé-ma]', trans: 'Dilema' },
        { word: 'Position', phonetic: '[po-zí-shon]', trans: 'Posición' },
        { word: 'Situation', phonetic: '[si-tchu-éi-shon]', trans: 'Situación' },
        { word: 'Advice', phonetic: '[ad-váis]', trans: 'Consejo' },
        { word: 'Suggestion', phonetic: '[sag-dzhés-tchon]', trans: 'Sugerencia' },
        { word: 'Warning', phonetic: '[uór-ning]', trans: 'Advertencia' },

        { word: 'Imagine', phonetic: '[i-má-dzhin]', trans: 'Imaginar' },
        { word: 'Suppose', phonetic: '[sa-póuz]', trans: 'Suponer' },
        { word: 'Assume', phonetic: '[a-siúm]', trans: 'Asumir' },
        { word: 'Predict', phonetic: '[pri-díkt]', trans: 'Predecir' },
        { word: 'Prevent', phonetic: '[pri-vént]', trans: 'Prevenir' },
        { word: 'Avoid', phonetic: '[a-vóid]', trans: 'Evitar' },
        { word: 'Happen', phonetic: '[já-pen]', trans: 'Suceder' },
        { word: 'Occur', phonetic: '[o-kér]', trans: 'Ocurrir' },
        { word: 'Result', phonetic: '[ri-zált]', trans: 'Resultar' },
        { word: 'Cause', phonetic: '[koz]', trans: 'Causar' },
        { word: 'Produce', phonetic: '[pro-diús]', trans: 'Producir' },
        { word: 'Melt', phonetic: '[melt]', trans: 'Derretir' },
        { word: 'Freeze', phonetic: '[fríz]', trans: 'Congelar' },
        { word: 'Boil', phonetic: '[bóil]', trans: 'Hervir' },
        { word: 'Burn', phonetic: '[bern]', trans: 'Quemarse' },
        { word: 'Win', phonetic: '[uin]', trans: 'Ganar' },
        { word: 'Lose', phonetic: '[lúz]', trans: 'Perder' },
        { word: 'Fail', phonetic: '[féil]', trans: 'Fallar / Reprobar' },
        { word: 'Succeed', phonetic: '[sak-síd]', trans: 'Tener éxito' },
        { word: 'Pass', phonetic: '[pas]', trans: 'Aprobar / Pasar' },
        { word: 'Accept', phonetic: '[ak-sépt]', trans: 'Aceptar' },
        { word: 'Refuse', phonetic: '[ri-fiúz]', trans: 'Rechazar' },
        { word: 'Reject', phonetic: '[ri-zhékt]', trans: 'Rechazar' },
        { word: 'Choose', phonetic: '[chúz]', trans: 'Elegir' },
        { word: 'Select', phonetic: '[se-lékt]', trans: 'Seleccionar' },
        { word: 'Decide', phonetic: '[di-sáid]', trans: 'Decidir' },
        { word: 'Change', phonetic: '[chéindzh]', trans: 'Cambiar' },
        { word: 'Modify', phonetic: '[mó-di-fai]', trans: 'Modificar' },
        { word: 'Improve', phonetic: '[im-prúv]', trans: 'Mejorar' },
        { word: 'Worsen', phonetic: '[wér-sen]', trans: 'Empeorar' },
        { word: 'Affect', phonetic: '[a-fékt]', trans: 'Afectar' },
        { word: 'Influence', phonetic: '[ín-flu-ens]', trans: 'Influenciar' },
        { word: 'Require', phonetic: '[ri-kuáier]', trans: 'Requerir' },
        { word: 'Depend', phonetic: '[di-pénd]', trans: 'Depender' },
        { word: 'Rely', phonetic: '[ri-lái]', trans: 'Confiar / Depender' },
        { word: 'Consider', phonetic: '[kon-sí-der]', trans: 'Considerar' },
        { word: 'Hesitate', phonetic: '[hé-zi-teit]', trans: 'Dudar / Vacilar' },
        { word: 'Doubt', phonetic: '[dáut]', trans: 'Dudar' },
        { word: 'Trust', phonetic: '[trast]', trans: 'Confiar' },
        { word: 'Promise', phonetic: '[pró-mis]', trans: 'Prometer' },
        { word: 'Threaten', phonetic: '[thré-ten]', trans: 'Amenazar' },
        { word: 'Warn', phonetic: '[uórn]', trans: 'Advertir' },
        { word: 'Advise', phonetic: '[ad-váiz]', trans: 'Aconsejar' },
        { word: 'Suggest', phonetic: '[sag-zhést]', trans: 'Sugerir' },
        { word: 'Recommend', phonetic: '[re-ko-ménd]', trans: 'Recomendar' },
        { word: 'Suffer', phonetic: '[sá-fer]', trans: 'Sufrir' },
        { word: 'Survive', phonetic: '[ser-váiv]', trans: 'Sobrevivir' },
        { word: 'Escape', phonetic: '[es-kéip]', trans: 'Escapar' },
        { word: 'Protect', phonetic: '[pro-tékt]', trans: 'Proteger' },
        { word: 'Save', phonetic: '[séiv]', trans: 'Salvar / Ahorrar' },

        { word: 'Hypothetical', phonetic: '[jai-po-thé-ti-kal]', trans: 'Hipotético' },
        { word: 'Imaginary', phonetic: '[i-má-dzhi-ne-ri]', trans: 'Imaginario' },
        { word: 'Probable', phonetic: '[pró-ba-bl]', trans: 'Probable' },
        { word: 'Improbable', phonetic: '[im-pró-ba-bl]', trans: 'Improbable' },
        { word: 'Likely', phonetic: '[láik-li]', trans: 'Probable' },
        { word: 'Unlikely', phonetic: '[an-láik-li]', trans: 'Improbable' },
        { word: 'Real', phonetic: '[rí-al]', trans: 'Real' },
        { word: 'Unreal', phonetic: '[an-rí-al]', trans: 'Irreal' },
        { word: 'Possible', phonetic: '[pó-si-bl]', trans: 'Posible' },
        { word: 'Impossible', phonetic: '[im-pó-si-bl]', trans: 'Imposible' },
        { word: 'Certain', phonetic: '[sér-ten]', trans: 'Cierto' },
        { word: 'Uncertain', phonetic: '[an-sér-ten]', trans: 'Incierto' },
        { word: 'Risky', phonetic: '[rís-ki]', trans: 'Riesgoso' },
        { word: 'Safe', phonetic: '[séif]', trans: 'Seguro' },
        { word: 'Dangerous', phonetic: '[déin-dzhe-ros]', trans: 'Peligroso' },
        { word: 'Beneficial', phonetic: '[be-ne-fí-shal]', trans: 'Beneficioso' },
        { word: 'Harmful', phonetic: '[járm-ful]', trans: 'Dañino' },
        { word: 'Crucial', phonetic: '[krú-shal]', trans: 'Crucial' },
        { word: 'Vital', phonetic: '[vái-tal]', trans: 'Vital' },
        { word: 'Essential', phonetic: '[e-sén-shal]', trans: 'Esencial' },
        { word: 'Optional', phonetic: '[óp-sho-nal]', trans: 'Opcional' },
        { word: 'Flexible', phonetic: '[flék-si-bl]', trans: 'Flexible' },
        { word: 'Strict', phonetic: '[estríkt]', trans: 'Estricto' },
        { word: 'Logical', phonetic: '[ló-dzhi-kal]', trans: 'Lógico' },
        { word: 'Illogical', phonetic: '[i-ló-dzhi-kal]', trans: 'Ilogico' },
        { word: 'Reasonable', phonetic: '[rí-zo-na-bl]', trans: 'Razonable' },
        { word: 'Unreasonable', phonetic: '[an-rí-zo-na-bl]', trans: 'Irrazonable' },
        { word: 'Ideal', phonetic: '[ai-dí-al]', trans: 'Ideal' },
        { word: 'Perfect', phonetic: '[pér-fekt]', trans: 'Perfecto' },
        { word: 'Imperfect', phonetic: '[im-pér-fekt]', trans: 'Imperfecto' },
        { word: 'Wealthy', phonetic: '[uél-thi]', trans: 'Rico / Acaudalado' },
        { word: 'Poor', phonetic: '[púr]', trans: 'Pobre' },
        { word: 'Generous', phonetic: '[dhzé-ne-ros]', trans: 'Generoso' },
        { word: 'Selfish', phonetic: '[sél-fish]', trans: 'Tacaño / Egoísta' },
        { word: 'Responsible', phonetic: '[ri-espón-sa-bl]', trans: 'Responsable' },
        { word: 'Irresponsible', phonetic: '[i-res-pón-sa-bl]', trans: 'Irresponsable' },
        { word: 'Aware', phonetic: '[a-wér]', trans: 'Consciente' },
        { word: 'Unaware', phonetic: '[an-a-wér]', trans: 'Inconsciente' },
        { word: 'Prepared', phonetic: '[pri-pérd]', trans: 'Preparado' },
        { word: 'Unprepared', phonetic: '[an-pri-pérd]', trans: 'Desprevenido' },

        { word: 'If', phonetic: '[if]', trans: 'Si (condicional)' },
        { word: 'Unless', phonetic: '[an-lés]', trans: 'A menos que' },
        { word: 'Provided that', phonetic: '[pro-vái-did dat]', trans: 'Siempre que / Con tal de que' },
        { word: 'As long as', phonetic: '[az long az]', trans: 'Siempre y cuando' },
        { word: 'In case', phonetic: '[in kéis]', trans: 'En caso de que' },
        { word: 'Otherwise', phonetic: '[á-der-uais]', trans: 'De lo contrario' },
        { word: 'Even if', phonetic: '[í-ven if]', trans: 'Incluso si' },
        { word: 'Supposing', phonetic: '[sa-póu-zing]', trans: 'Suponiendo que' },
        { word: 'Assuming that', phonetic: '[a-siú-ming dat]', trans: 'Asumiendo que' },
        { word: 'On condition that', phonetic: '[on kon-dí-shon dat]', trans: 'Bajo la condición de que' },
        { word: 'Or else', phonetic: '[or els]', trans: 'O si no' },
        { word: 'What if...?', phonetic: '[juót if]', trans: '¿Qué tal si...?' },
        { word: 'If I were you', phonetic: '[if ái wuer iú]', trans: 'Si yo fuera tú' },
        { word: 'Would', phonetic: '[wud]', trans: 'Auxiliar condicional (-aría)' },
        { word: 'Wouldn\'t', phonetic: '[wúd-nt]', trans: 'No (-aría)' },
        { word: 'Could', phonetic: '[kud]', trans: 'Podría' },
        { word: 'Might', phonetic: '[máit]', trans: 'Tal vez podría' },
        { word: 'In that case', phonetic: '[in dat kéis]', trans: 'En ese caso' },
        { word: 'If so', phonetic: '[if sóu]', trans: 'Si es así' },
        { word: 'If not', phonetic: '[if not]', trans: 'Si no' },
        { word: 'Under no circumstances', phonetic: '[án-der nóu sér-kom-stan-siz]', trans: 'Bajo ninguna circunstancia' },
        { word: 'Depending on', phonetic: '[di-pén-ding on]', trans: 'Dependiendo de' },
        { word: 'With or without', phonetic: '[uidth or uidth-aut]', trans: 'Con o sin' },
        { word: 'No matter what', phonetic: '[nóu má-ter juót]', trans: 'Sin importar qué' },
        { word: 'Regardless of', phonetic: '[ri-gárd-les ov]', trans: 'Independientemente de' },
        { word: 'In the event of', phonetic: '[in de i-vént ov]', trans: 'En el evento de' },
        { word: 'As a result', phonetic: '[az a ri-zált]', trans: 'Como resultado' },
        { word: 'Consequently', phonetic: '[kón-se-kuent-li]', trans: 'Por consiguiente' },
        { word: 'Therefore', phonetic: '[dér-for]', trans: 'Por lo tanto' },
        { word: 'Thus', phonetic: '[das]', trans: 'Así / Por ende' }
      ]
    },
    {
      id: 'b1_passive_voice',
      title: '3. Passive Voice: Present & Past Simple (Voz Pasiva)',
      summary: 'Desplazamiento del foco informativo del agente que realiza la acción hacia el objeto que la recibe.',
      description: 'La Voz Pasiva se utiliza cuando el objeto o la acción en sí es más relevante que el sujeto que la ejecuta, o cuando este sujeto es desconocido o irrelevante. Es ampliamente empleada en textos académicos, periodísticos y técnicos.',
      grammar: 'Transformación Gramatical:\n- Activa: Sujeto + Verbo + ObjetoDirecto. (ej. "The chef cooks the meal").\n- Pasiva: ObjetoDirecto + Verbo To Be (conjugado) + Verbo Principal en Pasado Participio + (by + Agente).\n\nModelos por Tiempo Gramatical:\n1. Present Simple Passive:\n - Structure: Sujeto + am / is / are + Participio Pasado.\n Ejemplo: "English is spoken all over the world." / "The cars are manufactured in Germany."\n2. Past Simple Passive:\n - Structure: Sujeto + was/ were + Participio Pasado.\n Ejemplo: "The telephone was invented by Alexander Graham Bell in 1876."',
      examples: [
        'Present Passive: "Millions of emails are sent every single day."',
        'Past Passive: "The famous painting was stolen from the museum last night."',
        'Agente omitido: "The suspect was arrested early this morning."',
        'Forma Interrogativa Pasiva: "Were you informed about the schedule change?"'
      ],
      vocabulary: [

        { word: 'Agent', phonetic: '[éi-dzhent]', trans: 'Agente (quien realiza la acción)' },
        { word: 'Action', phonetic: '[ák-shon]', trans: 'Acción' },
        { word: 'Object', phonetic: '[ób-dzhekt]', trans: 'Objeto' },
        { word: 'Subject', phonetic: '[sáb-dzhekt]', trans: 'Sujeto' },
        { word: 'Focus', phonetic: '[fóu-kus]', trans: 'Foco / Enfoque' },
        { word: 'Emphasis', phonetic: '[ém-fa-sis]', trans: 'Enfasis' },
        { word: 'Invention', phonetic: '[in-vén-shon]', trans: 'Invención' },
        { word: 'Discovery', phonetic: '[dis-kó-ve-ri]', trans: 'Descubrimiento' },
        { word: 'Creation', phonetic: '[kri-éi-shon]', trans: 'Creación' },
        { word: 'Production', phonetic: '[pro-dák-shon]', trans: 'Producción' },
        { word: 'Manufacture', phonetic: '[ma-niu-fák-tchur]', trans: 'Manufactura / Fabricación' },
        { word: 'Construction', phonetic: '[kon-estrúk-shon]', trans: 'Construcción' },
        { word: 'Building', phonetic: '[bíl-ding]', trans: 'Edificio' },
        { word: 'Structure', phonetic: '[es-trúk-tchur]', trans: 'Estructura' },
        { word: 'Bridge', phonetic: '[bridzh]', trans: 'Puente' },
        { word: 'Document', phonetic: '[dó-kiu-ment]', trans: 'Documento' },
        { word: 'Report', phonetic: '[ri-pórt]', trans: 'Informe / Reporte' },
        { word: 'Article', phonetic: '[ár-ti-kl]', trans: 'Artículo' },
        { word: 'Book', phonetic: '[buk]', trans: 'Libro' },
        { word: 'Novel', phonetic: '[nó-vel]', trans: 'Novela' },
        { word: 'Painting', phonetic: '[péin-ting]', trans: 'Pintura' },
        { word: 'Sculpture', phonetic: '[es-kúl-ptchur]', trans: 'Escultura' },
        { word: 'Law', phonetic: '[lo]', trans: 'Ley' },
        { word: 'Bill', phonetic: '[bil]', trans: 'Proyecto de ley / Factura' },
        { word: 'Decision', phonetic: '[di-sí-zhon]', trans: 'Decisión' },
        { word: 'Crime', phonetic: '[kráim]', trans: 'Crimen' },
        { word: 'Robbery', phonetic: '[ró-be-ri]', trans: 'Robo' },
        { word: 'Investigation', phonetic: '[in-ves-ti-géi-shon]', trans: 'Investigación' },
        { word: 'Suspect', phonetic: '[sás-pekt]', trans: 'Sospechoso' },
        { word: 'Thief', phonetic: '[thíf]', trans: 'Ladrón' },
        { word: 'Police', phonetic: '[po-lís]', trans: 'Policía' },
        { word: 'Museum', phonetic: '[miu-zí-um]', trans: 'Museo' },
        { word: 'Factory', phonetic: '[fák-to-ri]', trans: 'Fábrica' },
        { word: 'Company', phonetic: '[kóm-pa-ni]', trans: 'Compañía / Empresa' },
        { word: 'Industry', phonetic: '[ín-das-tri]', trans: 'Industria' },
        { word: 'System', phonetic: '[sís-tem]', trans: 'Sistema' },
        { word: 'Service', phonetic: '[sér-vis]', trans: 'Servicio' },
        { word: 'Product', phonetic: '[pró-dakt]', trans: 'Producto' },
        { word: 'Goods', phonetic: '[gudz]', trans: 'Bienes / Mercancías' },
        { word: 'Parcel', phonetic: '[pár-sel]', trans: 'Paquete / Encomienda' },

        { word: 'Built', phonetic: '[bilt]', trans: 'Construido' },
        { word: 'Made', phonetic: '[méid]', trans: 'Hecho' },
        { word: 'Produced', phonetic: '[pro-diúst]', trans: 'Producido' },
        { word: 'Manufactured', phonetic: '[ma-niu-fák-tchord]', trans: 'Manufacturado' },
        { word: 'Created', phonetic: '[kri-éi-tid]', trans: 'Creado' },
        { word: 'Designed', phonetic: '[di-záind]', trans: 'Diseñado' },
        { word: 'Invented', phonetic: '[in-vén-tid]', trans: 'Inventado' },
        { word: 'Discovered', phonetic: '[dis-kó-verd]', trans: 'Descubierto' },
        { word: 'Written', phonetic: '[rí-ten]', trans: 'Escrito' },
        { word: 'Painted', phonetic: '[péin-tid]', trans: 'Pintado' },
        { word: 'Drawn', phonetic: '[dron]', trans: 'Dibujado' },
        { word: 'Composed', phonetic: '[kom-póuzd]', trans: 'Compuesto (Música/Texto)' },
        { word: 'Directed', phonetic: '[di-rék-tid]', trans: 'Dirigido' },
        { word: 'Performed', phonetic: '[per-fórmd]', trans: 'Interpretado / Realizado' },
        { word: 'Spoken', phonetic: '[espóu-ken]', trans: 'Hablado' },
        { word: 'Taught', phonetic: '[tot]', trans: 'Enseñado' },
        { word: 'Learned', phonetic: '[lernd]', trans: 'Aprendido' },
        { word: 'Understood', phonetic: '[an-der-stúd]', trans: 'Entendido' },
        { word: 'Known', phonetic: '[noun]', trans: 'Conocido' },
        { word: 'Seen', phonetic: '[sín]', trans: 'Visto' },
        { word: 'Heard', phonetic: '[jerd]', trans: 'Oído' },
        { word: 'Found', phonetic: '[fáund]', trans: 'Encontrado' },
        { word: 'Stolen', phonetic: '[estóu-len]', trans: 'Robado' },
        { word: 'Taken', phonetic: '[téi-ken]', trans: 'Tomado / Llevado' },
        { word: 'Given', phonetic: '[gí-ven]', trans: 'Dado' },
        { word: 'Sent', phonetic: '[sent]', trans: 'Enviado' },
        { word: 'Delivered', phonetic: '[di-lí-verd]', trans: 'Entregado' },
        { word: 'Shipped', phonetic: '[shipt]', trans: 'Enviado / Despachado' },
        { word: 'Paid', phonetic: '[péid]', trans: 'Pagado' },
        { word: 'Bought', phonetic: '[bot]', trans: 'Comprado' },
        { word: 'Sold', phonetic: '[sóuld]', trans: 'Vendido' },
        { word: 'Cleaned', phonetic: '[klínd]', trans: 'Limpiado' },
        { word: 'Repaired', phonetic: '[ri-pérd]', trans: 'Reparado' },
        { word: 'Fixed', phonetic: '[fikst]', trans: 'Arreglado' },
        { word: 'Restored', phonetic: '[ri-estórd]', trans: 'Restaurado' },
        { word: 'Damaged', phonetic: '[dá-midzhd]', trans: 'Dañado' },
        { word: 'Destroyed', phonetic: '[dis-tróid]', trans: 'Destruido' },
        { word: 'Broken', phonetic: '[bróu-ken]', trans: 'Roto' },
        { word: 'Arrested', phonetic: '[a-rés-tid]', trans: 'Arrestado' },
        { word: 'Caught', phonetic: '[kot]', trans: 'Atrapado' },
        { word: 'Investigated', phonetic: '[in-vés-ti-gei-tid]', trans: 'Investigado' },
        { word: 'Examine', phonetic: '[eg-zá-min]', trans: 'Examinar' },
        { word: 'Approved', phonetic: '[a-prúvd]', trans: 'Aprobado' },
        { word: 'Rejected', phonetic: '[ri-zhék-tid]', trans: 'Rechazado' },
        { word: 'Cancelled', phonetic: '[kán-seld]', trans: 'Cancelado' },
        { word: 'Postponed', phonetic: '[poust-póund]', trans: 'Postergado' },
        { word: 'Delayed', phonetic: '[di-léid]', trans: 'Retrasado' },
        { word: 'Announced', phonetic: '[a-náunst]', trans: 'Anunciado' },
        { word: 'Informed', phonetic: '[in-fórmd]', trans: 'Informado' },
        { word: 'Notified', phonetic: '[nó-ti-faid]', trans: 'Notificado' },

        { word: 'Passive', phonetic: '[pá-siv]', trans: 'Pasivo' },
        { word: 'Active', phonetic: '[ák-tiv]', trans: 'Activo' },
        { word: 'Unknown', phonetic: '[an-nóun]', trans: 'Desconocido' },
        { word: 'Anonymous', phonetic: '[a-nó-ni-mos]', trans: 'Anónimo' },
        { word: 'Irrelevant', phonetic: '[i-ré-le-vant]', trans: 'Irrelevante' },
        { word: 'Unimportant', phonetic: '[an-im-pór-tant]', trans: 'Sin importancia' },
        { word: 'Official', phonetic: '[o-fí-shal]', trans: 'Oficial' },
        { word: 'Formal', phonetic: '[fór-mal]', trans: 'Formal' },
        { word: 'Academic', phonetic: '[a-ka-dé-mik]', trans: 'Académico' },
        { word: 'Scientific', phonetic: '[sai-en-tí-fik]', trans: 'Científico' },
        { word: 'Historical', phonetic: '[jis-tó-ri-kal]', trans: 'Histórico' },
        { word: 'Traditional', phonetic: '[tra-dí-sho-nal]', trans: 'Tradicional' },
        { word: 'Original', phonetic: '[o-rí-dzhi-nal]', trans: 'Original' },
        { word: 'Handmade', phonetic: '[jánd-meid]', trans: 'Hecho a mano' },
        { word: 'Automatic', phonetic: '[o-to-má-tik]', trans: 'Automático' },
        { word: 'Imported', phonetic: '[im-pór-tid]', trans: 'Importado' },
        { word: 'Exported', phonetic: '[eks-pór-tid]', trans: 'Exportado' },
        { word: 'Local', phonetic: '[lóu-kal]', trans: 'Local' },
        { word: 'Global', phonetic: '[glóu-bal]', trans: 'Global' },
        { word: 'National', phonetic: '[ná-sho-nal]', trans: 'Nacional' },
        { word: 'International', phonetic: '[in-ter-ná-sho-nal]', trans: 'Internacional' },
        { word: 'Public', phonetic: '[pá-blik]', trans: 'Público' },
        { word: 'Private', phonetic: '[prái-vit]', trans: 'Privado' },
        { word: 'Secret', phonetic: '[sí-kret]', trans: 'Secreto' },
        { word: 'Confidential', phonetic: '[kon-fi-dén-shal]', trans: 'Confidencial' },
        { word: 'Stolen', phonetic: '[estóu-len]', trans: 'Robado' },
        { word: 'Lost', phonetic: '[lost]', trans: 'Perdido' },
        { word: 'Found', phonetic: '[fáund]', trans: 'Encontrado' },
        { word: 'Damaged', phonetic: '[dá-midzhd]', trans: 'Dañado' },
        { word: 'Intact', phonetic: '[in-tákt]', trans: 'Intacto' },
        { word: 'Safe', phonetic: '[séif]', trans: 'Seguro' },
        { word: 'Secured', phonetic: '[si-kiúrd]', trans: 'Asegurado' },
        { word: 'Protected', phonetic: '[pro-ték-tid]', trans: 'Protegido' },
        { word: 'Exposed', phonetic: '[eks-póuzd]', trans: 'Expuesto' },
        { word: 'Required', phonetic: '[ri-kuái-erd]', trans: 'Requerido' },
        { word: 'Mandatory', phonetic: '[mán-da-to-ri]', trans: 'Obligatorio' },
        { word: 'Allowed', phonetic: '[a-láud]', trans: 'Permitido' },
        { word: 'Forbidden', phonetic: '[for-bí-den]', trans: 'Prohibido' },
        { word: 'Prohibited', phonetic: '[pro-jí-bi-tid]', trans: 'Prohibido' },
        { word: 'Accepted', phonetic: '[ak-sép-tid]', trans: 'Aceptado' },

        { word: 'By', phonetic: '[bai]', trans: 'Por (indica el agente)' },
        { word: 'With', phonetic: '[uidth]', trans: 'Con (indica el instrumento)' },
        { word: 'It is said that', phonetic: '[it iz sed dat]', trans: 'Se dice que' },
        { word: 'It is believed that', phonetic: '[it iz bi-lívd dat]', trans: 'Se cree que' },
        { word: 'It is known that', phonetic: '[it iz nóun dat]', trans: 'Se sabe que' },
        { word: 'It is expected that', phonetic: '[it iz eks-pék-tid dat]', trans: 'Se espera que' },
        { word: 'It was reported that', phonetic: '[it woz ri-pór-tid dat]', trans: 'Se reportó que' },
        { word: 'As reported', phonetic: '[az ri-pór-tid]', trans: 'Según lo reportado' },
        { word: 'According to', phonetic: '[a-kór-ding tu]', trans: 'De acuerdo con' },
        { word: 'In conclusion', phonetic: '[in kon-klú-zhon]', trans: 'En conclusión' },
        { word: 'For example', phonetic: '[for eg-zám-pl]', trans: 'Por ejemplo' },
        { word: 'Such as', phonetic: '[satch az]', trans: 'Tales como' },
        { word: 'In general', phonetic: '[in dhzé-ne-ral]', trans: 'En general' },
        { word: 'Generally speaking', phonetic: '[dhzé-ne-ra-li espí-king]', trans: 'Hablando en general' },
        { word: 'Widely', phonetic: '[uáid-li]', trans: 'Ampliamente' },
        { word: 'Commonly', phonetic: '[kó-mon-li]', trans: 'Comúnmente' },
        { word: 'Originally', phonetic: '[o-rí-dzhin-a-li]', trans: 'Originalmente' },
        { word: 'Initially', phonetic: '[i-ní-shal-i]', trans: 'Inicialmente' },
        { word: 'Eventually', phonetic: '[i-vén-tchu-a-li]', trans: 'Eventualmente / Al final' },
        { word: 'Finally', phonetic: '[fái-na-li]', trans: 'Finalmente' },
        { word: 'Recently', phonetic: '[rí-sent-li]', trans: 'Recientemente' },
        { word: 'In the past', phonetic: '[in de past]', trans: 'En el pasado' },
        { word: 'Nowadays', phonetic: '[náu-a-deis]', trans: 'Hoy en día' },
        { word: 'Currently', phonetic: '[ká-rent-li]', trans: 'Actualmente' },
        { word: 'At present', phonetic: '[at pré-zent]', trans: 'Al presente' },
        { word: 'Without doubt', phonetic: '[uidth-aut dáut]', trans: 'Sin duda' },
        { word: 'Of course', phonetic: '[ov kors]', trans: 'Por supuesto' },
        { word: 'As a consequence', phonetic: '[az a kón-se-kuens]', trans: 'Como consecuencia' },
        { word: 'Due to', phonetic: '[diú tu]', trans: 'Debido a' },
        { word: 'Because of', phonetic: '[bi-kóz ov]', trans: 'A causa de' }
      ]
    },
    {
      id: 'b1_reported_speech',
      title: '4. Reported Speech: Statements & Questions (Estilo Indirecto)',
      summary: 'Técnicas gramaticales para transmitir lo dicho por otra persona sin citar textualmente.',
      description: 'El Estilo Indirecto (Reported Speech) se utiliza para comunicar las palabras de otra persona ajustando los tiempos verbales hacia el pasado (Backshifting), modificando los pronombres personales, demostrativos y las referencias de tiempo/lugar.',
      grammar: 'Reglas Gramaticales y Cambios Temporales (Backshifting):\n- Direct Present Simple -> Reported Past Simple (Ej: "I like tea" -> He said he liked tea).\n- Direct Present Continuous -> Reported Past Continuous (Ej: "I am working" -> She said she was working).\n- Direct Past Simple / Present Perfect -> Reported Past Perfect (Ej: "I bought a car" -> He said he had bought a car).\n- Direct Will -> Reported Would / Can -> Could.\n- Say vs. Tell: "Say" no requiere objeto indirecto obligatorio (He said that...). "Tell" exige el objeto indirecto persona (He told me that...).\n- Questions: Las preguntas reportadas adoptan orden afirmativo (sin auxiliar do/did). Preguntas Yes/No utilizan "if/whether". Preguntas con Wh- conservan la palabra interrogativa.',
      examples: [
        'Declaración Directa: "I will call you tomorrow" -> Indirecta: "She told me that she would call me the next day."'
      ]
    }
  ]
};